### ISSUE TITLE
Thumbnail preview from Ideamaker Slicer

### ISSUE THREAD

**Issue by modmt** [Arksine/moonraker#100]
[test.zip](https://github.com/Arksine/moonraker/files/6041615/test.zip)

Hello, 
I want go ask if it is possible to extract a thumbnail preview from an Ideamaker sliced file to show it in Mainsail?
I asked this also in the Mainsail Git.
https://github.com/meteyou/mainsail/issues/180

If i understood right there is the possibility in Ideamaker to wrote Out an additional .Data File, which contains a Picture for displaying the model on the Raise3D Machines. But I do not know how this could be used.

Could you help me with this?
I can provide you an Ideamaker files if necessary.

Thank you in advance.
Matthias

Edit: in attachment you can find an example of the data file and the gcode wth the data included exported from Ideamarker.

**Comment by Arksine** [comment]
Unfortunately there is little I can do with this without some sort of specification.   The data file is a binary.  There is some Base64 encoded data at the end of the gcode file as well.  Without some guidance as to how to interpret this data it isn't possible to do anything with it.

**Comment by modmt** [comment]
OK, thank you. No problem. Maybe I have to ask the Ideamaker team how to handle the file (or at least if it's possible to extract an picture). I will come back to you if I know more.

**Comment by Arksine** [comment]
Since discussion here seems to have concluded I'm going to go ahead and close this issue.  If ideamaker wants to provide details on how to parse their thumbnails I'm open to adding support in Moonraker.
