### ISSUE TITLE
Upload from PrusaSlicer not working anymore

### ISSUE THREAD

**Issue by nicedevil007** [Arksine/moonraker#111]
Heya, I recently updated to the latest build of moonraker. Now PrusaSlicer isn't working anmore with direct upload / start print.

I get this message:
![image](https://user-images.githubusercontent.com/17103076/110137291-f90d4c80-7dd0-11eb-8b46-d7d7651943a0.png)

What I tryed to fix it:

1. Rebooting the printer (unplug/replug power)
2. Rebooting the raspberry pi (host reboot)
3. Restarting moonraker (service reboot)

Nothing helped so far. 

Uploading via Fluidd WebUI still works.

**Comment by Arksine** [comment]
Hi.  You need add [octoprint_compat] to moonraker.conf and restart the service.  

For future reference it is a good idea to check [user_changes.md](https://github.com/Arksine/moonraker/blob/master/docs/user_changes.md) if you have an issue to make sure that isn't related to a recent config change.

**Comment by nicedevil007** [comment]
> Hi. You need add [octoprint_compat] to moonraker.conf and restart the service.
> 
> For future reference it is a good idea to check [user_changes.md](https://github.com/Arksine/moonraker/blob/master/docs/user_changes.md) if you have an issue to make sure that isn't related to a recent config change.

sry, didn't saw this, added and working again :) Thank you!
