### ISSUE TITLE
Feature request: Resource monitor plugin

### ISSUE THREAD

**Issue by ihrapsa** [Arksine/moonraker#116]
Hey, are there any plans to add a resource monitor plugin into Moonraker? I know there's the temperature plugin for the SoC and mcu but no cpu load or ram usage.
Thanks! 🙂

**Comment by Arksine** [comment]
CPU load is reported by Klipper, as far as I know both Fluidd and Mainsail have support for it.

**Comment by ihrapsa** [comment]
> CPU load is reported by Klipper, as far as I know both Fluidd and Mainsail have support for it.

Yeah, sorry. The issue was oppened before that was introduced into fluidd/mainsail frontend.
