### ISSUE TITLE
[FR] print queue and/or number of copies

### ISSUE THREAD

**Issue by Hywelmartin** [Arksine/moonraker#127]
I'm currently building a belted ejection printer so that I can produce a lot of parts of the same thing.. 

 set a specific number of copies and/or a print queue would be nice

I'm not sure where this FR should be placed..  but Moonraker seems like the right place to me...

**Comment by Arksine** [comment]
Yes, this kind of functionality would need support in mooraker, then it could be added to clients.  I'll look into a "print queue" when I get a chance.

**Comment by Arksine** [comment]
Moonraker now has support for a job queue.  I believe that Mainsail has an early implementation in its latest beta release.
