### ISSUE TITLE
Shelly with the timer setting not working properly

### ISSUE THREAD

**Issue by onfoot** [Arksine/moonraker#146]
The timer property in the Shelly power config allows to perform a delayed power off and it's noted in the docs that we want to do a power _on_ so the turn off timer will be set on Shelly side and it will eventually power off once the timer expires.

The issue is that the `_process_request` func as of 3 months ago checks the current state and if the device is already on, it doesn't do the on with off timer trick.

I think it would be reasonable to modify the Shelly device state handling so that if there is a timer and the state is supposed to be _off_, it instead sends the on with off timer request, instead of us having to work around that in the macros/commands on the "client" side.

Edit: And also, when shelly is sent a turn=off request with a timer set, it turns back on after the timer expires. ;) I can make a PR with appropriate fixes if that's okay.

**Comment by Arksine** [comment]
A PR with the appropriate fixes would be great.  The Shelly functionality was user contributed and I do not own one of these devices, so it would be difficult to apply and test fixes myself.  Thanks.
