### ISSUE TITLE
Octoprint compat API state is always operational 

### ISSUE THREAD

**Issue by Komet** [Arksine/moonraker#147]
The Octoprint compat API (/api/printer) always reports state.text "Operational" even when printing. Therefore flags.operational is always true and the others like paused, printing, cancelling are always false. 

Moonraker v0.5.0-18-ge8f6862
Klipper v0.9.1-421

**Comment by Arksine** [comment]
Thanks.  This should be resolved by commit 5783604.

**Comment by Komet** [comment]
Oh wow, what a quick reaction and fix, thank you! I've just checked it out and it's working great.
