### ISSUE TITLE
FileManager is not handling thumbnails properly when copying or moving gcode files

### ISSUE THREAD

**Issue by emtrax-ltd** [Arksine/moonraker#162]
When copying or moving (also renaming) gcode files their existing thmbnails are not handled properly - they only disappearing.

I'm not sure if this is a bug or more a feature request - beacause there is no code yet for handling this.

**Comment by Arksine** [comment]
I responded to this comment in the  issue you created in the Fluidd repository.  It will be fixed when #159 is merged.

**Comment by Arksine** [comment]
The inotify branch has been merged, so this issue should now be resolved.
