### ISSUE TITLE
Lowercase transformation makes machine service control for MoonCord and KlipperScreen failed.

### ISSUE THREAD

**Issue by henkyprayoga** [Arksine/moonraker#172]
on machine.py:

<pre><code>
     async def _handle_service_request(self, web_request: WebRequest) -> str:
        name: str = web_request.get('service').lower()
        action = web_request.get_endpoint().split('/')[-1]
        if name == "moonraker":
            if action != "restart":
</code></pre>

**Comment by Arksine** [comment]
Thanks.  This should be fixed by commit def6b365facc7eab364c823d5b5a244aa682204a.

**Comment by henkyprayoga** [comment]
Wow that is fast! Thank you very much!
