### ISSUE TITLE
Control board pins as power plugin output

### ISSUE THREAD

**Issue by davide-molino** [Arksine/moonraker#173]
I will connect a 12V led strip to one of the heater output on my skr and be able to control it via power plugin, but I can only choose between raspberry gpio and smart plugs. Is it possible to add such a function?

**Comment by Arksine** [comment]
Unfortunately not.  Moonraker has limited access to GPIOs on the host machine that may be used with the `power` component.  You will have to use Klipper to control GPIOs on attached MCUs.

**Comment by pedrolamas** [comment]
@davide-molino this is now implemented via [Klipper Device](https://moonraker.readthedocs.io/en/latest/configuration/#klipper-device-configuration) in `power`!
