### ISSUE TITLE
Software Update section gone after Moonraker update

### ISSUE THREAD

**Issue by Roycinger** [Arksine/moonraker#187]
Hi,

I just updated moonraker via the Fluidd inbuilt software update solution.
After that, I dont see the software update section anymore in Fluidd, neither for Fluidd, Klipper and OS packages. 
Also, I'm getting an error that the Moonraker has failed plugins:
![image](https://user-images.githubusercontent.com/7791335/124282099-bbd08580-db4a-11eb-961a-0e9d053dffe6.png)

I'm suspecting that the syntax of the update manager changed.
Before, I had this in my moonraker.conf:
![image](https://user-images.githubusercontent.com/7791335/124282169-d145af80-db4a-11eb-98ca-7ebe7b8482f2.png)

According to the github documentation, the syntax is different now (I can be wrong here).

Any help is appreciated.

**Comment by Arksine** [comment]
Right, those options were deprecated quite some time ago and were recently removed.  It would now look something like this
```
[update_manger]

[update_manager client fluidd]
type: web
repo: cadrie/fluidd
path: /home/pi/fluidd
```

**Comment by Roycinger** [comment]
Thank you, I didn't notice that the old syntax style was deprecated. 

This solved it for me!
