### ISSUE TITLE
Update manager KlipperScreen broken since Update

### ISSUE THREAD

**Issue by nicedevil007** [Arksine/moonraker#191]
Heya,

I recently updated to latest Moonraker version and changed the updatemanager to the new documentation.

It did work for fluidd but not for KlipperScreen. What am I doing wrong?

```
[update_manager KlipperScreen]
type: git_repo
path: /home/pi/KlipperScreen
origin: https://github.com/jordanruthe/KlipperScreen.git
env: /home/pi/.KlipperScreen-env/bin/python
requirements: scripts/KlipperScreen-requirements.txt
install_script: scripts/KlipperScreen-install.sh
```

**Comment by Arksine** [comment]
I found a typo.  I will have it corrected shortly.

**Comment by nicedevil007** [comment]
I was just on the run to upload my log :D haha

**Comment by Arksine** [comment]
Fix is up.  You might need to comment out / remove your clients to get the UM to load, update moonraker, then add them back.

**Comment by nicedevil007** [comment]
![image](https://user-images.githubusercontent.com/17103076/124956685-84fde200-e018-11eb-98c4-d3415801f3be.png)

it is fixed :) thank you!
