### ISSUE TITLE
Allow Pull w/ Rebase in Repo Debug Mode

### ISSUE THREAD

**Issue by BlueDragonX** [Arksine/moonraker#196]
Would it be acceptable to add a flag to update_manager that would allow repos to be updated using `pull --rebase` rather than a simple `pull`? This would be helpful where local changes are in progress (such a updates to extras modules). If this seems reasonable then I can issue a PR in the near future.

**Comment by Arksine** [comment]
Seems like a good idea and is a very small patch so I went ahead and implemented it and pushed the change.  Thanks.
