### ISSUE TITLE
Incorrect info in the Moonraker configuration for klippy uds setting

### ISSUE THREAD

**Issue by lincolnep** [Arksine/moonraker#20]
Trying to setup a second instance of Moonraker and Mainsail and found an issue with the https://github.com/Arksine/moonraker/blob/master/docs/installation.md#moonraker-configuration-moonrakerconf doco

It states:
**klippy_address:** /tmp/klippy_uds
   The address of Unix Domain Socket used to communicate with Klippy. Default
   is /tmp/klippy_uds

After going through the code and testing this should be.
**klippy_uds_address:** /tmp/klippy_uds

otherwise both moonraker services talk to the default klipper uds.

**Comment by Arksine** [comment]
Thanks, I will fix the documentation shortly.
