### ISSUE TITLE
After latest update no more timelapse

### ISSUE THREAD

**Issue by SA7BNT** [Arksine/moonraker#214]
After the latest update (v0.7.1-36-gf1523ef) i cant use this snippet anymore in the moonraker.conf
 Something i missed??

<img width="560" alt="Bildschirmfoto 2021-08-22 um 19 22 00" src="https://user-images.githubusercontent.com/35367117/130364207-cdab463b-8e19-4fe3-ba6a-3a2de477a60e.png">

**Comment by FrYakaTKoP** [comment]
@SA7BNT  checked the timelapse.py still works with v0.7.1-36 totally fine 

can you post your moonraker.log?

**Comment by SA7BNT** [comment]
> @SA7BNT checked the timelapse.py still works with v0.7.1-36 totally fine
> 
> can you post your moonraker.log?

[moonraker.log](https://github.com/Arksine/moonraker/files/7027925/moonraker.log)

**Comment by FrYakaTKoP** [comment]
```
  File "/home/pi/moonraker/moonraker/components/timelapse.py", line 7
    <!DOCTYPE html>
    ^
```
It looks like you updated the timelapse script too and downloaded it manually on github. But you need to download the raw script, not the html representation on github

connect to ssh and execute following commands:
```
cd ~/moonraker/moonraker/components/
curl -O https://raw.githubusercontent.com/FrYakaTKoP/moonraker/dev-timelapse/moonraker/components/timelapse.py
```
that should fix the timelapse issue

(also there are alot of klippy disconnects in your log but that's another topic)

**Comment by SA7BNT** [comment]
> ```
>   File "/home/pi/moonraker/moonraker/components/timelapse.py", line 7
>     <!DOCTYPE html>
>     ^
> ```
> 
> It looks like you updated the timelapse script too and downloaded it manually on github. But you need to download the raw script, not the html representation on github
> 
> connect to ssh and execute following commands:
> 
> ```
> cd ~/moonraker/moonraker/components/
> curl -O https://raw.githubusercontent.com/FrYakaTKoP/moonraker/dev-timelapse/moonraker/components/timelapse.py
> ```
> 
> that should fix the timelapse issue
> 
> (also there are alot of klippy disconnects in your log but that's another topic)

Thanks for help, you make my day. 
Ya i know, but still pretty rookie @klipper 
Will have a closer look. 
Thanks for the hint

**Comment by FrYakaTKoP** [comment]
your welcome!

again join the klipper discord there is a lot of information to get and also people willing to help

**Comment by SA7BNT** [comment]
> your welcome!
> 
> again join the klipper discord there is a lot of information to get and also people willing to help

thanks mate
Will look after klipper discord
