### ISSUE TITLE
Documentation: api_key_path should be api_key_file

### ISSUE THREAD

**Issue by randellhodges** [Arksine/moonraker#22]
Documentation for the api key says:
`api_key_path`
https://github.com/Arksine/moonraker/blob/master/docs/installation.md

But the code says:
`api_key_file`
https://github.com/Arksine/moonraker/blob/8440a10b9e7a9e8fec53a90d57959380fd8753c5/moonraker/authorization.py#L22

**Comment by Arksine** [comment]
Thanks, documentation has been fixed.
