### ISSUE TITLE
Suggestion: Improve error message for non jwt "Authorization" header

### ISSUE THREAD

**Issue by Maximilian-Staab** [Arksine/moonraker#220]
I had an issue where a proxy **using http basic authentification** would **break** `check_authorized`.

https://github.com/Arksine/moonraker/blob/b04064081330bd5464442c0d8e7e4d93420a7859/moonraker/components/authorization.py#L436

If the value isn't a json web token, the trusted domains are never checked and this error is generated:

```
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/components/authorization.py", line 537, in _check_json_web_token
    return self._decode_jwt(auth_token)
  File "/home/pi/moonraker/moonraker/components/authorization.py", line 436, in _decode_jwt
    message, sig = token.rsplit('.', maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/moonraker-env/lib/python3.7/site-packages/tornado/web.py", line 1681, in _execute
    result = self.prepare()
  File "/home/pi/moonraker/moonraker/websockets.py", line 461, in prepare
    self.current_user = auth.check_authorized(self.request)
  File "/home/pi/moonraker/moonraker/components/authorization.py", line 597, in check_authorized
    jwt_user = self._check_json_web_token(request)
  File "/home/pi/moonraker/moonraker/components/authorization.py", line 539, in _check_json_web_token
    raise HTTPError(401, str(e))
tornado.web.HTTPError: HTTP 401: Unauthorized (not enough values to unpack (expected 2, got 1))
```

The intended behavior should probably either be **a better log message**, or to **fall back to the other authorization methods**.

**Comment by Arksine** [comment]
This should be resolved with commit dfb8da6,

**Comment by Maximilian-Staab** [comment]
It does work as intended, but a possible issue could be a leaked password through sharing `moonraker.log`. I think logging a authorization header & JWT decoding issue without the header value is enough for debugging purposes.

**Comment by Arksine** [comment]
If the only potential issue was basic auth in the header I would agree, however its possible that some other invalid value could exist in the header.  Its useful to log exactly what is in the header in an effort to troubleshoot it.  I agree that it could leak the password in the log, however this is likely going to be a very rare case.  No user is directed to use Basic Auth to access Moonraker's endpoints.

**Comment by Maximilian-Staab** [comment]
I have a similar proposal: 

Only allow JWT via bearer tokens and reject all non bearer values with `401` & send back a [WWW-Authenticate](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate): [Bearer](https://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml). This would remove the need to differentiate between JWT and `username:password` checks. Invalid JWT should still be logged of course. 

I do see pretty big issue with this, though: Existing applications expect non bearer tokens to work as well. However, I don't know which applications use this way of authentication.

**Comment by Arksine** [comment]
I did go ahead and filter out Basic auth so the user/password isnt leaked.  I don't think Moonraker needs to worry about sending back a response header.  There are several ways to pass authentication depending on the configuration.

**Comment by Maximilian-Staab** [comment]
Looking good, thanks for the quick fix!
