### ISSUE TITLE
[FR] Add option to not install Nginx dependency via install script

### ISSUE THREAD

**Issue by pandel** [Arksine/moonraker#229]
Hi!

It would be very nice if you would add a command line parameter to avoid installing Nginx via install-script. I am using Moonraker on a machine with another web proxy server together with a Fluidd Docker instance on another machine, which is running great in general.

To avoid having to modify your install script this option could be a handy improvement.

Regards,
Holger

**Comment by Arksine** [comment]
Since nginx is no longer installed as a Moonraker dependency I'm going to close this as resolved.
