### ISSUE TITLE
Fix for "sudo_fix.sh Error: visudo: Command not found" on Armbian?

### ISSUE THREAD

**Issue by Swift-Tester** [Arksine/moonraker#241]
_Sadly the `sudo_fix.sh` script is intended for CustomPiOS derived distros (such as Octopi).  It isn't surprising that it does not work on Armbian.  I don't own any devices that run Armbian so I can not provide any official support for them.  If someone is able to come up with a script that gives Moonraker permission to run sudo without a password on Armbian I would be happy to review it and merge if it looks good._

_Originally posted by @Arksine in https://github.com/Arksine/moonraker/issues/92#issuecomment-776615280_

What about calling "visudo" via "sudo visudo"? (Like other utilities in this script).
Hope this won't break CustomPiOS compatibility, and this definitely works on my Armbian.
[sudo_fix.patch.txt](https://github.com/Arksine/moonraker/files/7335579/sudo_fix.patch.txt)

**Comment by KwadFan** [comment]
Hi, I think your patch doesnt affect custompios. So, LGTM.

**Comment by sjqlwy** [comment]
TRY THIS:
`echo 'export PATH="/sbin:/usr/sbin:$PATH"' >> ~/.bashrc && source ~/.bashrc`

**Comment by Arksine** [comment]
I believe that this issue is resolved as the suggestion was merged in #298.
