### ISSUE TITLE
[FR] Seperate OS update manager from klipper stack updaters

### ISSUE THREAD

**Issue by cbc02009** [Arksine/moonraker#248]
I would like to be able to use moonraker update manager to update my klipper stack and mods on my Arch linux install. As long as I have a working install script for my distribution and git installed, the update manager should be able to update things like mainsail and klipper without issue, unless there's something obvious that I'm missing.

Separating them out might also make it easier to add OS update manager support for other linux distros as well.

**Comment by Arksine** [comment]
They aren't tightly coupled, however Klipper (and Moonraker) do rely on the system updater to handle dependencies.  It is possible to set the `enable_system_updates` option to `False`, which should allow the update to proceed.  Python dependencies should still be updated but package dependencies will need to be manually updated if they change.

The [documentation](https://moonraker.readthedocs.io/en/latest/configuration/#update_manager) has more details.
