### ISSUE TITLE
Useing Timelapse with exern Script

### ISSUE THREAD

**Issue by Damada42** [Arksine/moonraker#250]
give there a config to trigger a Timelapsepic to external cam? At the moment i use a Gopro but i change timelapse.py on line183.
from 'cmd = "wget " + self.snapshoturl + " -O " \ .....' i change it to 'cmd = "bash " + self.snapshoturl' so it works but the question is there a setting without rewriting the file? 

in moonraker.conf change the snapshoturl:
#snapshoturl: http://192.168.0.41:8080/?action=snapshot
snapshoturl: /home/pi/scripts/goprosnap.sh

**Comment by Arksine** [comment]
Discussion seems to have concluded here so I'm going to close this issue.  As Fry mentioned, discussion related to the timelapse plugin would get more attention on his repo. Thanks.
