### ISSUE TITLE
Resetting print history totals

### ISSUE THREAD

**Issue by Rudis1261** [Arksine/moonraker#252]
I seem to be able to view the general information from the moonraker database using `curl localhost:7125/server/database/item?namespace=moonraker`, but I am looking to reset the history for my printer. I have re-used a MCU and PI on a new printer. And would like to keep track of how much I have printed, but all my old history is still there.

I was able to delete all the individual stats with this endpoint. 
```shell
curl localhost:7125/server/history/job?all=true -X "DELETE"
```

I tried using compound keys for the namespace and or key params, but I wasn't able to refine the moonraker namespace data, do be able to delete it. Is there something in place already that would allow me to do so? Or is it something that can be added to clear those totals as well?

**Comment by Arksine** [comment]
This is now available via the [reset_totals](https://moonraker.readthedocs.io/en/latest/web_api/#reset-totals) endpoint.

**Comment by Rudis1261** [comment]
That's awesome thank you!! 😬 🥳

**Comment by Rudis1261** [comment]
Worked like a charm thanks again!
