### ISSUE TITLE
[FR] Add MQTT Last Will And Testament (LWT) support

### ISSUE THREAD

**Issue by pedrolamas** [Arksine/moonraker#262]
A good practice on MQTT is to have the client set a Last Will And Testament (LWT) that the broker will publish automatically if the device connection terminates in a non-conformant way.

It's like telling the MQTT broker "if I get disconnected for some reason publish this message to this topic".

Paho-MQTT does have support for this as shown [here](https://mntolia.com/mqtt-last-will-testament-explained-with-examples/) so hopefully it should be an easy improvement to add!

**Comment by Arksine** [comment]
This seems useful and as you said it isn't difficult to add.  I suppose it comes down to hashing out implementation details, specifically which topic the will should be set to.  Presumably it would make sense to apply this to the status topic given that it is the one clients will be listening to, however we could make it configurable as well.

**Comment by pedrolamas** [comment]
This is now complete, so closing this FR now.
