### ISSUE TITLE
API /machine/device_power/devices return value issue

### ISSUE THREAD

**Issue by ikirt** [Arksine/moonraker#269]
System Information
----------------------------
Repository Name: moonraker
Path: /home/pi/moonraker
Remote: origin
Branch: master
Remote URL: https://github.com/Arksine/moonraker.git
Current Commit SHA: ca27c2cf100c47fcbc52d60aa6d61121775a2d9d
Upstream Commit SHA: ca27c2cf100c47fcbc52d60aa6d61121775a2d9d
Current Version: v0.7.1-142
Upstream Version: v0.7.1-142
Is Dirty: False
Is Detached: False
Commits Behind: 0

I noticed while trying to parse the /machine/device_power/devices API endpoint in python I kept getting the following error:

```
>>> json.loads(req.text)['result']['devices']['status']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: list indices must be integers or slices, not str
```

If I take a step back and look at everything returned I see:

```
>>> json.loads(req.text)
{'result': {'devices': [{'device': 'wifi_switch', 'status': 'on', 'locked_while_printing': False, 'type': 'tplink_smartplug'}]}}
```

I noticed the 2 square brackets surrounding the device section which causes the python json module in python to fault.

Reviewing another endpoint which I can successfully parse, /printer/objects/query?print_stats I see the following results(Postman):

```
{
    "result": {
        "status": {
            "print_stats": {
                "print_duration": 0.0,
                "total_duration": 0.0,
                "filament_used": 0.0,
                "filename": "",
                "state": "standby",
                "message": ""
            }
        },
        "eventtime": 5506.406120532
    }
}
```

**Comment by Arksine** [comment]
That is because the `devices` field contains a list of devices.  The appropriate way to handle this in a python client would be something like
```python
devices = json.loads(req.text)['result']['devices']
for dev in devices:
  print(dev['status'])
```
or if you wanted to do a one liner that just returns the status of the first device:
```python
json.loads(req.text)['result']['devices'][0]['status']
```

One thing to keep in mind is different endpoints will have return values that are unique to the state they return.  The API documentation will typically give an example and explanation of what is being returned.

**Comment by ikirt** [comment]
Thank you for pointing this out, I will review the API documents again !

**Comment by Arksine** [comment]
As there has been no further discussion I'm going to go ahead and close this issue.  Thanks.
