### ISSUE TITLE
SuperSlicer with supports - layer height mismatch

### ISSUE THREAD

**Issue by vajonam** [Arksine/moonraker#270]
I am seeing an issue with the current version of Super Slicer which generates supports with variable layer heights. 

https://github.com/prusa3d/PrusaSlicer/issues/553

However as this regex https://github.com/Arksine/moonraker/blob/ca27c2cf100c47fcbc52d60aa6d61121775a2d9d/moonraker/components/file_manager/metadata.py#L214

Matches all layer heights. It kind of messes up the layer count. Actual is 490, 125.1 (total height) / 0.3 (layer_height) = 417. 

![image](https://user-images.githubusercontent.com/152501/141607678-306b02f1-15d7-4835-8400-5761c6c392d9.png)
[Amazing Kup (8)_PETG_0.3mm.zip](https://github.com/Arksine/moonraker/files/7531472/Amazing.Kup.8._PETG_0.3mm.zip)

Since we get the number of Layer changes by counting `m` matches 

https://github.com/Arksine/moonraker/blob/ca27c2cf100c47fcbc52d60aa6d61121775a2d9d/moonraker/components/file_manager/metadata.py#L217

in the code. can we not deduce the layer height instead of just dividing the total height by layer height? This will provide an accurate count of layer height when using supports with PrusaSlicer based slicers. We can fall back to `total_height/layer_height` if we cannot find any regex matches for `;BEFORE_LAYER_CHANGE\n(?:.*\n)?;(\d+\.?\d*)` 

I can provide a PR if you think this acceptable?

**Comment by vajonam** [comment]
Maybe just 

`count (matches)` here as well? 

https://github.com/Arksine/moonraker/blob/ca27c2cf100c47fcbc52d60aa6d61121775a2d9d/moonraker/components/file_manager/metadata.py#L221

**Comment by Arksine** [comment]
Moonraker does not actually report the layer count, Fluidd is making that calculation.  The method you are referring to reports object height, so it is behaving as expected.

We can't deduce the layer count by counting matches as Moonraker doesn't analyze the entire gcode file.  IMO, the proper way handle this would be for the slicer itself to report the layer count in the metadata.  Moonraker could then extract it and report it.

**Comment by vajonam** [comment]
I can add a post GCode to add a total layers when the g-code is produced. Any specific format?

**Comment by vajonam** [comment]
Will open a issue for SuperSlicer and link it with this.

**Comment by Arksine** [comment]
If SuperSlicer implements this then I'm ok with adding support to Moonraker.  I don't need a particular format, but it should probably match the way SuperSlicer reports metadata for other items.

**Comment by vajonam** [comment]
I have opened a FR will see how this goes. I will leave this open until we get a resolution on the Super Slicer ticket. https://github.com/supermerill/SuperSlicer/issues/1886

if we assume it will something like, which matches the super slicer format.

```
; total_layer_count = {total_layer_count} 

```

then I can add it the custom G-code section now and we can test this.

**Comment by vajonam** [comment]
@Arksine this is now fixed / added to SuperSlicer. Can you also look to add the parsing for this. https://github.com/supermerill/SuperSlicer/issues/1886

**Comment by Arksine** [comment]
Ok, I'll look at adding it.   From the commit it appears that the layer count is not going to be presented as you proposed.  It appears that is going be placed at the end of the gcode as:
```
; total layers count = {layer_count}
```
Can you confirm?

**Comment by vajonam** [comment]
That is what the commit says. SuperSlicer puts all meta info at the end of the file. So I think that is accurate. However since this will be quite / quick fast we can wait for the release to see how it looks in reality before getting this closed out. 

What are your thoughts on klipper accurately reporting current layer? right now that is guesstimate assuming equal layer heights. is possible for klipper to report the exact layer based on gcode comments? 

I think as the UI get features like g-code preview this will become important to show an accurate representation of the status of the print. 

I will also ask the klipper question in the kipper discord.

**Comment by vajonam** [comment]
I can confirm.

`; total layers count = 300` 

to the latest release of SuperSlicer

**Comment by Arksine** [comment]
Support for this should be merged.
