### ISSUE TITLE
Issue with Prusa Slicer and Moonraker

### ISSUE THREAD

**Issue by chickenmcniggels** [Arksine/moonraker#278]
Whenever I try to upload to Moonraker this error shows up.. The slicer says that it can communicate with OctoPrint, when I hit that test button but whenever I hit upload this error pops up

![2021-11-17 (5)](https://user-images.githubusercontent.com/94556032/142247086-5b5939c4-bd6d-4b31-bf65-8b41082fea0b.png)

I've searched the entire Internet and cannot find an answer to this problem. Is someone familiar with this error?

**Comment by Afterschnitzel** [comment]
check your printer.cfg if you have the right path to gcode folder:

`[virtual_sdcard]
path: ~/gcode_files`

**Comment by Afterschnitzel** [comment]
![image](https://user-images.githubusercontent.com/60582475/142919695-73c104f6-910b-498d-a205-5100452de4c5.png)

**Comment by chickenmcniggels** [comment]
This fixed it! Thank you

**Comment by Arksine** [comment]
Since this appears to be fixed I am closing this issue.
