### ISSUE TITLE
Service seems active but does nothing.

### ISSUE THREAD

**Issue by holmlrs** [Arksine/moonraker#28]
**Linux distro**
Armbian 20.08.1 Bionic with Linux 5.8.5-sunxi

**Issue**
Everything installs fine. Klipper installs and connects to printer no problem (see klippy.log). However, the moonraker API service does nothing. It installs and starts without problem. But no connection with klipper is made, port 7125 is not listening and the api is not generating a log. Trying to connect to http://<printer-ip>:7125/printer/info gives connecton refused as expected with a port that is not listening.

Any ideas as to how this occurs and how to fix this? 
Thanks in advance!

klippy.log:
[klippy.log](https://github.com/Arksine/moonraker/files/5397306/klippy.log)
printer.cfg (uploaded as txt due to github compatibility):
[printer.txt](https://github.com/Arksine/moonraker/files/5397309/printer.txt)

edit: more info added

**Comment by Arksine** [comment]
The first thing I would check is the python version.  Moonraker requires Python 3.7.

If your python version is correct, you could try running the application manually to see if an error is sent to stderr:
```
python3 ~/moonraker/moonraker/moonraker.py
````

**Comment by Makhaira** [comment]
I may be having a similar issue. Trying to install at the moment and whilst the install script completes successfully I cannot get moonraker to start (no evidence in the klippy.log).

Running the moonraker.py check originally threw up an error with not having tornado so I've added that to python3 and now I can run moonraker.py but nothing happens.

Interestingly in the klippy.log it's reporting my python version as 2.7 even though I have 3.7 installed and have even tried setting a bash alias to redirect python to python3.

**Comment by Arksine** [comment]
Klippy requires Python 2, so it will report 2.7 as the verision.  Moonraker requires Python 3.7 +.   If moonraker.py is failing prior to creating /tmp/moonraker.log then it is likely still missing a dependency, running manually should produce an error.  Unfortunately I do not own any devices that run Armbian so I am unable to provide much meaningful help.  If the virtualenv installed correctly, running a slightly different command might be useful.

```
~/moonraker-env/bin/python ~/moonraker/moonraker/moonraker.py
```

**Comment by Arksine** [comment]
Since this discussion has concluded I am going to close this.  Given that moonraker now runs as a systemd service it is now possible to possible to use journalctl to view the log as well as any error that may have prevented Moonraker from starting, ie:
```
sudo journalctl -u moonraker.service
```
