### ISSUE TITLE
Feature Request: Cancel objects

### ISSUE THREAD

**Issue by Coffee0297** [Arksine/moonraker#29]
The only reson i can't get myself to switch to moonracker and a interface is the missing cancel objects. its allready implemented in the gcode from most slicers so it shuld not be an issue to implement that. Im just too dumb to try :D

**Comment by Arksine** [comment]
This is something that is planned for the future.  It is going to require a Klippy extra since it is Klipper that parses gcode, and there is an issue there with this feature request.  You can track it at KevinOConnor/klipper#3375.

**Comment by Arksine** [comment]
This is now implemented.  Nice to knock out an issue almost two years old 😄
