### ISSUE TITLE
Moonraker fails to connect if GitHub down. 

### ISSUE THREAD

**Issue by bill-orange** [Arksine/moonraker#290]
For around an hour today all GitHub sites were down. During this time Moonraker , if disconnected would not reconnect. It’s possible that I would connect eventually but the timeout must have been at least 10 min.

I would not expect GitHub access to be necessary for Moonraker  to work smoothly. I believe there should be a prompt fall-through on a failure to connect.

**Comment by Arksine** [comment]
I just pushed a set of patches that should help with this issue.  There are some limitations as to what can be done without access to github, but it shouldn't prevent the update manager from starting.
