### ISSUE TITLE
Moonraker disconnects

### ISSUE THREAD

**Issue by webel69** [Arksine/moonraker#293]
Hi, 
I am having a problem with random moonraker disconnects both on a Raspberry pi 4 running fluidpi and also a raspberry 2 running the same.  On the pi4 the issue started after updating from Fluidpi 16.2 using the Fluiddpi dashboard. After the update the disconnects were random., but made uploading gcode from the web ui extremely difficult.   
I started from scratch installing 16.2 on the raspberry pi2 with a fresh install and even reflashed klipper on the ender 3 max. Crashes wew much less frequent, but It still has issues when uploading gcode. with in a few seconds of the window opening up to select the gcode file to upload moonraker disconnects..  I did update moonraked acording to another post relating to diconnects.  I have attached the most recent log.  Hope you can help.
[moonraker.log](https://github.com/Arksine/moonraker/files/7630804/moonraker.log)

**Comment by Arksine** [comment]
This log is an older version of moonraker, but it appears you are having local networking issues.  I don't see where fluidd tries to connect, but what I do see is a failure for to reach `api.github.com`.  Make sure your wifi signal is good, if possible try connecting via ethernet to see if it resolves the issue.

**Comment by webel69** [comment]
There were multiple moonraker logs,  not in front of the computer now, which do you need?

Sent from Yahoo Mail on Android 
 
  On Wed, Dec 1, 2021 at 5:34 PM, Eric ***@***.***> wrote:   


This log is an older version of moonraker, but it appears you are having local networking issues. I don't see where fluidd tries to connect, but what I do see is a failure for to reach api.github.com. Make sure your wifi signal is good, if possible try connecting via ethernet to see if it resolves the issue.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Arksine** [comment]
The other logs are likely just rollovers. If you uploaded the latest log that is ok.  According to the log, the verision of Moonraker on your system is nearly 200 commits behind master.  Also, its having a problem reaching github, which is either a wan issue or a DNS issue.

**Comment by Arksine** [comment]
As there has been no further comment I'm going to close this issue.  If you need further assistance please join the Klipper discord.    You can request help in the `moonraker` channel.  Though as mentioned above, this appears to be a local networking issue.
