### ISSUE TITLE
Error parsing network information

### ISSUE THREAD

**Issue by mrwilby** [Arksine/moonraker#300]
### What happened

I have a canbus toolhead configured on my machine. The logic in machine.py, specifically https://github.com/Arksine/moonraker/blob/master/moonraker/components/machine.py#L440 appears to assume that all network interfaces have a mac address.

```
2021-12-05 04:40:02,400 [moonraker.py:_init_klippy_connection()] - GCode Output Subscribed
2021-12-05 04:40:04,018 [machine.py:parse_network_interfaces()] - Error processing network update
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/components/machine.py", line 440, in parse_network_interfaces
    'mac_address': interface['address'],
KeyError: 'address'
```

A partial extract of my network listing:

```
[...,
{
	"ifindex": 4,
	"ifname": "can0",
	"flags": ["NOARP", "UP", "LOWER_UP", "ECHO"],
	"mtu": 16,
	"qdisc": "pfifo_fast",
	"operstate": "UP",
	"group": "default",
	"txqlen": 128,
	"link_type": "can",
	"addr_info": []
}]
```

This is causing a huge number of errors in the moonraker logs which makes finding other blocking issues more challenging

### What did you expect to happen

No errors reported for canbus adaptors in the moonraker logs

### How to reproduce

Install & configure a network device that does not have a mac address

**Comment by Arksine** [comment]
Thanks.  This should be fixed in commit ac73036857cc1ca83df072dd94bf28eb9d0ed8b0.
