### ISSUE TITLE
[FR] Permit "toggle" command for tasmota power device

### ISSUE THREAD

**Issue by Swift-Tester** [Arksine/moonraker#308]
### Is your feature request related to a problem? Please describe

Tasmota does support "toggle" command, but as for now attempt to use it via moonraker results in
`[power.py:set_device_power()] - Invalid state received: toggle`

### Describe the solution you'd like

Please consider permitting "toggle" command for tasmota power device.
"Quick and dirty" hack of power.py like
```
226c226
<         if status not in ["on", "off"]:
---
>         if status not in ["on", "off", "toggle"]:
665c665
<         if command in ["on", "off"]:
---
>         if command in ["on", "off", "toggle"]:
```
works, but I'm not sure about side effects for other types of devices.

**Comment by Arksine** [comment]
I went ahead and added this when making some changes to support mqtt devices in d0b1621bd5077ce0a62c7d05a0fb756396908053.  It should work for all devices, as toggling doesn't rely on any specific device commands.
