### ISSUE TITLE
Add macros to PanelDue

### ISSUE THREAD

**Issue by paulhew69** [Arksine/moonraker#32]
Is there some basic instructions on how to add macros to the PanelDue, please.
I could do with my Z_TILT_ADJUST on the touchpanel, and some others. 

Thanks in advance.
Paul.

**Comment by Arksine** [comment]
There is an example [here](https://github.com/Arksine/moonraker/blob/master/docs/installation.md#paneldue-plugin).  If you add Z_TILT_ADJUST to the `macros` option it will be available.   You can add any `gcode_macro` or extended gcode.

**Comment by paulhew69** [comment]
Thanks for your help, greatly appreciated.
Regards

Paul
