### ISSUE TITLE
klipper wont connect to printer moon raker error

### ISSUE THREAD

**Issue by metric1578** [Arksine/moonraker#321]
### What happened

can't seem to connect to printer with klipper/moonraker. attached is a klippy log:

{"error": {"code": 404, "message": "Not Found", "traceback": "Traceback (most recent call last):\n\n  File \"/home/pi/moonraker-env/lib/python3.7/site-packages/tornado/web.py\", line 1704, in _execute\n    result = await result\n\n  File \"/home/pi/moonraker/moonraker/app.py\", line 639, in get\n    self.root, absolute_path)\n\n  File \"/home/pi/moonraker-env/lib/python3.7/site-packages/tornado/web.py\", line 2778, in validate_absolute_path\n    raise HTTPError(404)\n\ntornado.web.HTTPError: HTTP 404: Not Found\n"}}

### What did you expect to happen

I expected to connect to printer via fluidd. I tried updating rpi4 but didn't seem to help. I can log on fluidd site and see my config files but it just won't connect to printer.

### How to reproduce

installed latest release fluidd,klipper,moonraker and updated.

**Comment by Arksine** [comment]
You will need to supply `moonraker.log` and `klippy.log`.  My suspicion is that you don't have the unix socket enabled.

**Comment by Arksine** [comment]
As discussion seems to have concluded I'm going to close this.  If you need any further assistance I suggest trying the discord.

**Comment by gknops** [comment]
I am seeing the same issue, was there any discussion with possible hints?

**Comment by yw4z** [comment]
same error appeared for me after updating klipper from fluidd UI. i guess this method changed an environment variable

[moonraker.log](https://github.com/user-attachments/files/15936524/moonraker.log)

probably i will uninstall and reinstall klipper to fix it.  but why :)

**Comment by Romano26** [comment]
Hello, I have the same problem after a Klipper update.

**Comment by Key-Alex** [comment]
I encountered the same problem, I can't find a solution. Can anyone suggest specific steps to solve it?

**Comment by Romano26** [comment]
I used kiauh to restore the previous version of klipper

**Comment by Key-Alex** [comment]
I found the solution completely by accident, in one of the threads it was written -> https://github.com/Arksine/moonraker/issues/113#issuecomment-791932455
> You are not experiencing the same issue. You need to add [octoprint_compat] to moonraker.conf and restart the service
This helped me
