### ISSUE TITLE
wled serial: MCU and WLED will not connect to klipper/moonraker when MCU and ESP have same usb id

### ISSUE THREAD

**Issue by sydrbloc** [Arksine/moonraker#330]
### What happened

There is a condition in which klipper and moonraker might not know how to communicate to klippy and an wled esp via serial appropriately if both devices are connected to the same Linux device (raspberry pi), have the same USB ID and are being addressed in the config via /dev/serial/by-id

### What did you expect to happen

For klipper to connect to MCU and moonraker to connect to wled esp. 

### How to reproduce

Creality board 4.2.2 and Wemos D1 mini is where I discovered the bug. Both use 1a86:7523 USB to serial devices.
![mcu_wled usbid collision](https://user-images.githubusercontent.com/81474838/149345700-76d1deba-6619-404d-a808-9e2438677e9f.png)

### Additional information

As a workaround I set my klipper.config to address the MCU by-path and moonraker.config wled serial to by-path as well. This might only be resolved by documentation for this condition if others also have the same problem. By doing this though there is another issue that the MCU and WLED will have to ensure they stay on the same physical USB ports or the configurations will have to change if they are moved to different physical USB ports.

**Comment by Arksine** [comment]
This is a system issue, Moonraker has no control over the USB IDs of connected devices.  When you have multiple devices with the same USB ID you must either use the `by-path` symbolic link or the direct location of the serial port.  Indeed, when using the `by-path` symbolic link you must update it if you change USB ports.

I'm not sure that this requires documentation in Moonraker, Klipper has [documentation](https://www.klipper3d.org/FAQ.html#wheres-my-serial-port) to this effect.  If this becomes a common question then perhaps it could go in an FAQ at some point.

**Comment by sydrbloc** [comment]
I agree. I am just making sure there is documentation and you are aware of the issue if it ever pops up again. Thank you for the response.
