### ISSUE TITLE
no moonraker connection. please check moonraker status and / or refresh

### ISSUE THREAD

**Issue by alessandro111297** [Arksine/moonraker#333]
### What happened

After Fluidd update in Fluidd API, there is this error "no moonraker connection. please check moonraker status and / or refresh"
<img width="2003" alt="Schermata 2022-01-16 alle 23 47 32" src="https://user-images.githubusercontent.com/82523513/149681293-89274fe1-389f-44a4-90b3-8d03e47da3ae.png">
This is the log file:
[fluidd-error.log.txt](https://github.com/Arksine/moonraker/files/7878098/fluidd-error.log.txt)
[moonraker.log.log](https://github.com/Arksine/moonraker/files/7878099/moonraker.log.log)
After this, I also tried to update moonraker and fluidd from kiuah in raspberry terminal but same problem 

I can see a repetition of same problem in fluidd-error.log: 

2022/01/16 22:26:51 [error] 445#445: *89 connect() failed (111: Connection refused) while connecting to upstream, client: 100.68.233.4, server: _, request: "GET /server/database/item?namespace=fluidd&key=uiSettings HTTP/1.1", upstream: "http://127.0.0.1:7125/server/database/item?namespace=fluidd&key=uiSettings", host: "100.66.8.95", referrer: "http://100.66.8.95/"

100.66.8.95 is (tailscale) raspberry, and 100.68.233.4 is (tailscale) pc 

same error when I try without vpn (tailscale): 

2022/01/16 22:11:44 [error] 445#445: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.226, server: _, request: "GET /server/database/item?namespace=fluidd&key=uiSettings HTTP/1.1", upstream: "http://127.0.0.1:7125/server/database/item?namespace=fluidd&key=uiSettings", host: "192.168.1.249", referrer: "http://192.168.1.249/"

192.168.1.249 is raspberry and 192.168.1.226 is my pc

**Comment by Arksine** [comment]
Presumably Moonraker failed to start after update, its possible that one or more new dependencies failed to install.
Run the following command and let me know what the output is:

```
sudo journalctl -xe -u moonraker.service
```

If there is traceback in there copy it over.  The other possibility is repo corruption, however I think that is unlikely.

**Comment by alessandro111297** [comment]
Solved,  installed dependecies with the command: ~/moonraker/scripts/install-moonraker.sh and finally work.
Thank you very much

**Comment by Dev-Mug** [comment]
> Presumably Moonraker failed to start after update, its possible that one or more new dependencies failed to install. Run the following command and let me know what the output is:
> 
> ```
> sudo journalctl -xe -u moonraker.service
> ```
> 
> If there is traceback in there copy it over. The other possibility is repo corruption, however I think that is unlikely.
> 
> Edit:
> 
> You could also try running the install script to make sure dependencies are updated:
> 
> ```
> ~/moonraker/scripts/install-moonraker.sh
> ```


This worked for me as well, Had the same issue. Thanks guys!

**Comment by d3dorsett** [comment]
I used kiauh to install klipper with fluidd. After a recent update, I got this error too. Running the script above also fixed my issue.

It appears these files did not get updated...
Downloading https://www.piwheels.org/simple/certifi/certifi-2021.10.8-py2.py3-none-any.whl (151 kB)
Downloading https://www.piwheels.org/simple/charset-normalizer/charset_normalizer-2.0.12-py3-none-any.whl (44 kB)
Downloading https://www.piwheels.org/simple/urllib3/urllib3-1.26.9-py2.py3-none-any.whl (155 kB)
Downloading https://www.piwheels.org/simple/requests/requests-2.27.1-py2.py3-none-any.whl (63 kB)

**Comment by anderfrank** [comment]
> Presumably Moonraker failed to start after update, its possible that one or more new dependencies failed to install. Run the following command and let me know what the output is:
> 
> ```
> sudo journalctl -xe -u moonraker.service
> ```
> 
> If there is traceback in there copy it over. The other possibility is repo corruption, however I think that is unlikely.
> 
> Edit:
> 
> You could also try running the install script to make sure dependencies are updated:
> 
> ```
> ~/moonraker/scripts/install-moonraker.sh
> ```

Thanks for this, helped fix my install after I had to rebuild.

**Comment by JamieKaybg** [comment]
> I had a similar problem, but solved by deleting the moonraker.conf file, uninstalling Moonraker and installing again.

I believe this will also put me back on track to resolving a bad gate way in moonraker.cfg, after changing the host server up address. My delima is I'm unsure how to get CLI in Moonraker seems this was a distribution from creality Sonic pad, installed on a Windows system. Any recommendations greatly appreciated. Is it possible to access CLI from Sonic pad

**Comment by Moxie15** [comment]
Where do I put the command?????

**Comment by clmcgrath** [comment]
for anyone coming here for the bad gateway error check your kllippy logs ,  i had an issue today where i uninstalled obico like 2 weeks ago but it didnt remove the include from moonraker moonraker hadnt restarted till today when i needed to reboot my pi moonraker refused to start and gave bad gateway errors i checked my log file and i was getting missing include file errors , checked my moon raker conf and the was an old include 
moral of the story always check your klippy logs if you are having errors

**Comment by clmcgrath** [comment]
> Where do I put the command?????

ssh into your printer to execute any non gcode specific command 
i would check your klippy logs forst tho 
which can be reached by ssh  if your moonraker isn't starting ==> cat ~/printer_data/logs/klippy.log

**Comment by zemlyanskii-artem** [comment]
вот такая же проблема . Не могу решить ! непонимаю куда вставлять ваши команды!

**Comment by lol12433** [comment]
i also have the same issue but on the home screen

**Comment by Joscal76** [comment]
Alguien puede ayudarme con el acceso al cambio para solucionar el mismo problema? 
Gracias de antemano

**Comment by lol12433** [comment]
to  joscal76: conseguir un nuevo chip EMC para la impresora.

**Comment by LoneSimba** [comment]
> вот такая же проблема . Не могу решить ! не понимаю куда вставлять ваши команды! удалял все ! сбрасывал до заводских не помогает! всети нет нигде нормальной информации

так надо по ssh к планшету подключиться, там же линукс обычный* (на самом деле там форк Tina linux, который сам по себе форк openwrt)

**Comment by lol12433** [comment]
just replace the emmc chip
