### ISSUE TITLE
Log to stdout for cases like docker

### ISSUE THREAD

**Issue by MagicRB** [Arksine/moonraker#34]
Currently moonraker logs to a file and the usual way of symlinking to /dev/stdout doesn't due to moonraker attempting to rotate the logs file. Therefore another process like tail or other must be used.

**Comment by Arksine** [comment]
This functionality is now available.  It will require that Moonraker is reinstalled, see the [user changes](https://github.com/Arksine/moonraker/blob/master/docs/user_changes.md#december-6th-2020) documentation.
