### ISSUE TITLE
moonraker keeps disconnecting/restarting

### ISSUE THREAD

**Issue by clf139** [Arksine/moonraker#347]
### What happened

Moonraker keeps disconnecting/restarting every couple of minutes

### What did you expect to happen

I expect moonraker to stay connected 

### How to reproduce

Continues to occur even after the following troubleshooting steps:

- Updated: moonraker, klipper, timelapse, fluidd, and OS packages

Logs and screenshots attached
![moonrakererror](https://user-images.githubusercontent.com/80653699/151170302-dc8852d1-0956-4014-b6c7-0a160ee7ff2d.PNG)
.
[moonraker (4).log](https://github.com/Arksine/moonraker/files/7941998/moonraker.4.log)
[klippy (3).log](https://github.com/Arksine/moonraker/files/7941996/klippy.3.log)
[fluidd-error.log](https://github.com/Arksine/moonraker/files/7942015/fluidd-error.log)

**Comment by Arksine** [comment]
There aren't any disconnections in moonraker.log.  This could be an issue with using nginx, you could try having fluidd connect to Moonraker directly via port 7125.  Otherwise it could be a local networking issue, or an issue with Fluidd.

**Comment by Arksine** [comment]
This issue has become inactive, so I am going to close it.  As mentioned, the issue could be nginx or a networking issue.
