### ISSUE TITLE
Updated moonraker

### ISSUE THREAD

**Issue by kshaub103** [Arksine/moonraker#365]
I was updating and I when to updated moonraker and now i am unable to print![image](https://user-images.githubusercontent.com/96362402/153786033-65be92fd-17c8-47ad-a39c-8e2934a884d4.jpeg)![image](https://user-images.githubusercontent.com/96362402/153786046-3950dda4-4a02-4109-beda-99b40e865c65.jpeg)

**Comment by zellneralex** [comment]
See https://docs.mainsail.xyz/faq/klipper_errors/command_format_mismatch

**Comment by Arksine** [comment]
Thanks Alex.  As mentioned, this is an issue with your Klipper installation.  You need to flash your mcu.

**Comment by Arksine** [comment]
I'm going to close this since it isn't related to Moonraker.  If you need further assistance please visit the Klipper discord or discourse.
