### ISSUE TITLE
Error when file name contains space (missing urldecode?)

### ISSUE THREAD

**Issue by technophreak** [Arksine/moonraker#368]
### What happened

Using Cura Octoprint to communicate with moonraker; I get the following error;
2022-02-15 17:30:41,492 [web.py:log_exception()] - 400 POST /api/files/moonraker/gcodes/V3_Fan+Cover.gcode (192.168.88.56): File does not exist

### Client

Other

### Browser

Chrome

### How to reproduce

Put a space in the job name in Cura

### Additional information

I'm pretty sure a urldecode is missing after the upload operation to refer to the file stored in virtual SD card to convert + into a space. Might also be good to check if we need to escape other characters (shell args?)

**Comment by Arksine** [comment]
Tornado automatically decodes and escapes the url.  This looks like a bug in Cura's Octoprint plugin.  Spaces in the path fragment must be percent encoded (ie: `%20`).  They can be escaped with a "+" in the query string or the form.

**Comment by Arksine** [comment]
Upon closer review, its possible that this is a bug in Moonraker.  Its possible that Octoprint is making a request based on what is in the location header returned by the upload.  It appears that it isn't being encoded correctly, I'll push a fix shortly and we'll see if it resolves the issue.

**Comment by Arksine** [comment]
Fix pushed.  Let me know if this still occurs.

**Comment by technophreak** [comment]
You're awesome, I will try this right away and report back.

**Comment by technophreak** [comment]
I confirm that after a simple pull and moonraker restart, this is now working as expected.

Thank you for such a fast response.
