### ISSUE TITLE
Error in Configuration Document

### ISSUE THREAD

**Issue by madmaximus00** [Arksine/moonraker#378]
### What happened

Under Secrets Configuration this is listed as the example, but there should be a colon after "home_assistant" 

it might also be helpful to state whether the token string should be in quotes or not.

{
    "mqtt_credentials": {
        "username": "mqtt_user",
        "password": "my_mqtt_password"
    },
    "home_assistant" {
      "token": "long_token_string"
    }
}

### Client

Other

### Browser

Other or N/A

### How to reproduce

check https://moonraker.readthedocs.io/en/latest/configuration/#accessing-secret-credentials

### Additional information

just a simple typo

**Comment by Arksine** [comment]
Thanks, this should be resolved in commit 0a2c1904c000a826c34b2d236864d9acf23c4019.

With regard to the quotes, I think its save to presume that if the user chooses to use json that they have an understanding of the format, in which all string values are quoted.  The documentation does note that advantage of `json` is that fields can be typed, whereas all values in the ini are assumed to be strings.
