### ISSUE TITLE
/machine/shutdown doesnt shutdown the RPI anymore

### ISSUE THREAD

**Issue by kolbenhans** [Arksine/moonraker#398]
### What happened

http POST /machine/shutdown doesnt shutdown the RPI anymore.

instead i receive the following Error:

`{
  "error": {
    "code": 405,
    "message": "Method Not Allowed",
    "traceback": "Traceback (most recent call last):\n\n  File \"/home/pi/moonraker-env/lib/python3.7/site-packages/tornado/web.py\", line 1704, in _execute\n    result = await result\n\n  File \"/home/pi/moonraker/moonraker/app.py\", line 600, in get\n    await self._process_http_request()\n\n  File \"/home/pi/moonraker/moonraker/app.py\", line 630, in _process_http_request\n    raise tornado.web.HTTPError(405)\n\ntornado.web.HTTPError: HTTP 405: Method Not Allowed\n"
  }
}`

I searched a bit and found the issue: #349  from january and tried to run the mentioned sh script:
`~/moonraker/scripts/set-policykit-rules.sh`

as well as the install script:
`~/moonraker/scripts/install-moonraker.sh`

i also did a reboot of the RPI but it still doesn't work.

### Client

Mainsail

### Browser

Chrome

### How to reproduce

open http://-mainsail-os-ip-/machine/shutdown in Browser (Chrome, Firefox, Edge)

**Comment by Arksine** [comment]
The `/machine/shutdown` endpoint requires a `POST` request.  When you navigate via the browser it performs a `GET` http request.

You will need to use Mainsail, or another client, to initiate the shutdown.  If there is an issue it will be logged in `moonraker.log`, which you can download and attach to this issue.

**Comment by kolbenhans** [comment]
yeah okay, understand. I did it with a POST Http request by node red so far.
But today i replaced my mqtt query with a ultimate filter node that changed the "0" string coming from iobroker to a boolean false in the payload, this was causing the issue.

Now it's fixed.

Neverless, thanks for the hint and help.
