### ISSUE TITLE
Changes to the Update Manager

### ISSUE THREAD

**Issue by Arksine** [Arksine/moonraker#410]
I recently pushed some changes to the update manager that users and developers should be aware of.  The primary points of concern are as follows:

1) The `web_beta` type has been deprecated.  A `channel` option has been introduced for extensions.  The `web` type may be set to `stable` or `beta`, the default value is `stable`.  If `web_beta` is set as the `type` then the channel will be set as `beta` and a the user will be warned.  This also applies to `zip_beta`, however I don't believe that type is currently in use.   Configuration for a beta `web` type might look like the following:
```ini
# moonraker.conf

# mainsail beta
[update_manager mainsail]
type: web
channel: beta
repo:  mainsail-crew/mainsail
path: ~/mainsail

# fluidd beta
[update_manager fluidd]
type: web
channel: beta
repo:  fluidd-core/fluidd
path: ~/fluidd

```
Stable releases can simply omit the `channel` option.  Refer to the specific front end documentation for more details, not all front ends have beta releases.

2) At popular request it is now possible to configure an extension to restart the `moonraker` and/or `klipper` services after an update. A new `manged_services` option has been added to facilitate this.  Some examples below:
```ini
# moonraker.conf

# Currently it isn't necessary to add the `managed_services` option to specify that a service
# restart itself, however it will be required in the future, thus it is recommended to make this
# change now
[update_manager KlipperScreen]
type: git_repo
path: ~/KlipperScreen
origin: https://github.com/jordanruthe/KlipperScreen.git
env: ~/.KlipperScreen-env/bin/python
requirements: scripts/KlipperScreen-requirements.txt
install_script: scripts/KlipperScreen-install.sh
managed_services: KlipperScreen

# Timelapse has a service that restarts klipper and moonraker.  With the
# new configuration it shouldn't be necessary as the update manager will
# restart both
[update_manager timelapse]
type: git_repo
primary_branch: main
path: ~/moonraker-timelapse
origin: https://github.com/mainsail-crew/moonraker-timelapse.git
managed_services: klipper moonraker

# Just an ordinary git repo, we don't want to restart anything so we add
# "is_system_service: False".
[update_manager just_a_repo]
type: git_repo
path: ~/just_a_repo
origin: https://github.com/fake_repo/just_a_repo
is_system_service: False
```

3) Moonraker now supports a `beta` channel for `git_repo` types.  Git repos on the beta channel will update to the latest tag rather than to the latest commit..  The default value of the `channel` option for `git_repos` is `dev`.

4) The above was implemented in part to support an upcoming beta release for Moonraker.  Currently Moonraker still defaults to the `dev` channel, however that will change to `beta` before I tag the next release.  This will be announced when it occurs.

**Comment by mortezafj** [comment]
# moonraker.conf

# Currently it isn't necessary to add the `managed_services` option to specify that a service
# restart itself, however it will be required in the future, thus it is recommended to make this
# change now
[update_manager KlipperScreen]
type: git_repo
path: ~/KlipperScreen
origin: https://github.com/jordanruthe/KlipperScreen.git
env: ~/.KlipperScreen-env/bin/python
requirements: scripts/KlipperScreen-requirements.txt
install_script: scripts/KlipperScreen-install.sh
managed_services: KlipperScreen

# Timelapse has a service that restarts klipper and moonraker.  With the
# new configuration it shouldn't be necessary as the update manager will
# restart both
[update_manager timelapse]
type: git_repo
primary_branch: main
path: ~/moonraker-timelapse
origin: https://github.com/mainsail-crew/moonraker-timelapse.git
managed_services: klipper moonraker

# Just an ordinary git repo, we don't want to restart anything so we add
# "is_system_service: False".
[update_manager just_a_repo]
type: git_repo
path: ~/just_a_repo
origin: https://github.com/fake_repo/just_a_repo
is_system_service: False
