### ISSUE TITLE
Moonraker returns GatewayTimeout for long running operations

### ISSUE THREAD

**Issue by lorenzodimauro97** [Arksine/moonraker#437]
### What happened

This happens regardless of using the regular Moonraker API or the Octoprint emulated API.

When launching long-running GCodes, such as a simple PID_CALIBRATE, moonraker will eventually return GatewayTimeout. No keep-alive header or timeout settings makes any difference to this.

Implementing WebSocket the way it's currently implemented is not an option, and it shouldn't be: there is no reason why the simple HTTP API shouldn't work for such operations, too.

### Client

Other

### Browser

Chrome

### How to reproduce

Using POSTMAN or equivalent, launch a long-running GCode (example: /printer/gcode/script?script=PID_CALIBRATE HEATER=extruder TARGET=210).

It will eventually return GatewayTimeout.

**Comment by Arksine** [comment]
Since this conversation seems to have concluded I am going to close this issue.
