### ISSUE TITLE
Temperature not editable on Mobile Device

### ISSUE THREAD

**Issue by SchwabJ** [Arksine/moonraker#438]
### What happened

Hello,
Since the last Version i cant edit the temperatures on mobile devices:

![Screenshot_20220528-081927](https://user-images.githubusercontent.com/93655993/170813228-51e32772-7720-4221-969b-b5da60532513.png)

Is this bug known? The previous verson works.

### Client

Mainsail

### Browser

Chrome

### How to reproduce

E.g. Pixel 6 Pro Android 12 with Chrome

### Additional information

v0.7.1-572-gd53cf27

**Comment by Creo2005** [comment]
> ### What happened
> Hello, Since the last Version i cant edit the temperatures on mobile devices:
> 
> ![Screenshot_20220528-081927](https://user-images.githubusercontent.com/93655993/170813228-51e32772-7720-4221-969b-b5da60532513.png)
> 
> Is this bug known? The previous verson works.
> 
> ### Client
> Mainsail
> 
> ### Browser
> Chrome
> 
> ### How to reproduce
> E.g. Pixel 6 Pro Android 12 with Chrome
> 
> ### Additional information
> v0.7.1-572-gd53cf27

Use Android app: Klipperoid or Mobileraker :)

**Comment by SchwabJ** [comment]
> 
> Use Android app: Klipperoid or Mobileraker :)

Not so fluffy as the web gui🙈

**Comment by Arksine** [comment]
This appears to be a bug in [Fluidd](https://github.com/fluidd-core/fluidd), you may want to report it there.

**Comment by matmen** [comment]
looks like this is mainsail, not fluidd ;)

**Comment by Arksine** [comment]
Oops, sorry, you are correct!  I have corrected the post

**Comment by SchwabJ** [comment]
Bug is fixed there in beta4. Thank you. My mistake.
