### ISSUE TITLE
[BUG] Slicer upload

### ISSUE THREAD

**Issue by Potattoe** [Arksine/moonraker#440]
### What happened

Hello, after complete raspberry reinstall i can’t upload files from slicer, i always get this error. I've tried changing ip adress, adding api key, creating new folder for gcodes and changing some settings in moonraker, but nothing helped.
![Screenshot_1](https://user-images.githubusercontent.com/106449027/170839519-d327d3a8-4917-4c21-8522-5a8087c3e6ab.png)

### Client

Fluidd

### Browser

Firefox

### How to reproduce

I don't know how to reproduce this issue.

**Comment by Arksine** [comment]
Most likely you don't have `[octoprint_compat]` in `moonraker.conf`.  The [documentation](https://moonraker.readthedocs.io/en/latest/configuration/#octoprint_compat) has details on its configuration.

**Comment by Potattoe** [comment]
I have [octoprint_compat] in moonraker.conf, i tried to reinstall moonraker again and it didn't help, i'm compleatly lost.. :/

**Comment by Arksine** [comment]
Please provide `moonraker.log`.  It should provide a clue as to what is going on.

**Comment by Potattoe** [comment]
I just reinstalled my whole raspberry again and it's working now, thanks for your help. <3
