### ISSUE TITLE
Invalid root path (gcodes)

### ISSUE THREAD

**Issue by linghaokeji** [Arksine/moonraker#446]
### What happened

I tried install klipper+moonraker+fluidd on debian buster and debian bulleyes use kiauh

### Client

Fluidd

### Browser

Chrome

### How to reproduce

install klipper+moonraker+fluidd with kiauh on orangepi's debian system (server version) No error is reported during the installation process

### Additional information

![微信截图_20220605020407](https://user-images.githubusercontent.com/106884033/172036377-e6ee2f66-98f4-41ec-9f91-2cb473384806.png)
![微信截图_20220605020320](https://user-images.githubusercontent.com/106884033/172036379-66f3f3df-998f-4c56-af07-0152d51e4497.png)
![微信截图_20220605132338](https://user-images.githubusercontent.com/106884033/172036411-924f7f0c-c87a-495f-8268-c2a1964ebc6c.png)

**Comment by Arksine** [comment]
Please attach the full `moonraker.log`.  Generally this error occurs when Moonraker has been unable to connect to Klipper.

**Comment by yu3000** [comment]
I found the same problem "Invalid root path",the attachment is my log with debug :true
please help, thanks.
[moonraker (1).log](https://github.com/Arksine/moonraker/files/9027776/moonraker.1.log)

**Comment by Arksine** [comment]
Moonraker needs to successfully connect to an instance of Klipper in the "ready" state at least once to retrieve the gcode path.  After its received Moonraker will save it in the database.   In the future I plan to change this behavior, where Moonraker dictates the path and Klipper's configuration must match.

FWIW, the log shows that the source has been modified, if the issue persists after fixing Klipper then I'll need you to reproduce with a pristine repo to be able to track down exactly what is happening.

**Comment by yu3000** [comment]
thanks for you fast reply.
I have clear my codes and recover to a pristine repo.
This is my current version.

fluidd
v1.18.2
UP TO DATE
klipper
v0.10.0-508-g1636a975
UP TO DATE
moonraker
v0.7.1-597-gd37f91c
UP TO DATE
OS Packages

[moonraker (2).log](https://github.com/Arksine/moonraker/files/9028528/moonraker.2.log)
[klippy (2).log](https://github.com/Arksine/moonraker/files/9028529/klippy.2.log)

**Comment by yu3000** [comment]
I want to provide more information.

I can find my mcu id by following commands
<<<<<<<<<<<<<<<<<<<
ls /dev/serial/by-id/*
/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0

but I can't connect to my mcu with following message.
<<<<<<<<<<<<<<<<<<
mcu 'mcu': Unable to connect
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Error configuring printer

**Comment by yu3000** [comment]
the problem has been fixed,thanks.

**Comment by Stars-world** [comment]
Can you tell me how you solved it? I have the same problem.

**Comment by Antynik** [comment]
I have the same problem too.

**Comment by Arksine** [comment]
Klipper must be able to enter the ready state before Moonraker can request the gcode path from it.  If you need assistance getting Klipper running the [Klipper Discourse](https://klipper.discourse.group/c/general-discussion/6) is the recommended forum for requesting assistance.  Make sure you include your logs (I suggest both klippy.log and moonraker.log) with your request.

There are also help channels on the Klipper Discord, however the nature of discord can make it more difficult for someone to see it.

**Comment by Antynik** [comment]
my mistake was that I configured the board without a printer

**Comment by yu3000** [comment]
You should excute the command by the following squence.
<<<<<<<<
sudo service klipper stop
make flash FLASH_DEVICE=/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0
sudo service klipper start
>>>>>>>>

Once the mcu connect successfully, the error "Invalid root path" will go.

**Comment by Arksine** [comment]
As this issue appears to be resolved I am going to go ahead and close it.  Thanks.
