### ISSUE TITLE
Query printer object status via MQTT doesn't seem to work

### ISSUE THREAD

**Issue by pedrolamas** [Arksine/moonraker#456]
### What happened

I'm sending the below to MQTT topic "ender3v2/moonraker/api/request":

```json
{
    "jsonrpc": "2.0",
    "method": "printer.objects.query",
    "params": {
        "objects": {
            "print_stats": null,
            "toolhead": ["position", "status"]
        }
    }
}
```

Sending this seems to do nothing, as I'm not getting any response back via MQTT.

I know Moonraker is actually getting this data because if I go and change the `method` to a fake one or even the `params.objects` to `params.something_else`, I will get an "ender3v2/moonraker/api/response" error message back telling me there was an error running the above.

### Client

Other

### Browser

Other or N/A

### How to reproduce

Configure MQTT in moonraker and then send this to the topic "<instance>/moonraker/api/request":

```json
{
    "jsonrpc": "2.0",
    "method": "printer.objects.query",
    "params": {
        "objects": {
            "print_stats": null,
            "toolhead": ["position", "status"]
        }
    }
}
```

**Comment by Arksine** [comment]
You need to include an "id" in the json-rpc request to get a response, ie:
```json
{
    "jsonrpc": "2.0",
    "method": "printer.objects.query",
    "params": {
        "objects": {
            "print_stats": null,
            "toolhead": ["position", "status"]
        }
    },
    "id": 1
}
```

**Comment by pedrolamas** [comment]
Oh, that's interesting, I assumed that was not a requirement as running the `printer.gcode.script` works just fine without it:

```json
{
  "jsonrpc": "2.0",
  "method": "printer.gcode.script",
  "params": {
    "script": "SET_PIN PIN=\"lights\" VALUE=0"
  }
}
```

**Comment by Arksine** [comment]
Yes, Moonraker will execute the request, however it only sends a response if an "id" is present per the jsonrpc spec.

**Comment by pedrolamas** [comment]
Got it now, thanks for clearing that! 🙂
