### ISSUE TITLE
Access gpio pins from Orange Pi Zero 2 and Orange Pi Win

### ISSUE THREAD

**Issue by acguardia** [Arksine/moonraker#489]
How can I access gpio pin from Orange Pi Zero 2 to turn on/off lights or SSR?
For example, with Raspberry Pi I can use:
[power Luzes]
type: gpio
pin: !gpiochip0/gpio04
off_when_shutdown: True
initial_state: off

**Comment by Arksine** [comment]
Please don't create announcements, they are reserved for developers only.

With regard to your question, I unfortunately can't be of use.  Presumably it would be similar to the Raspberry Pi, however it depends on the linux distribution.  I would recommend seeking assistance on the discord.
