### ISSUE TITLE
Notifier Apprise Homeassistant

### ISSUE THREAD

**Issue by wieluk** [Arksine/moonraker#490]
### What happened

I am trying to send notifications to homeassistant.
It works fine with apprise installed on the machine.

But when I try it on with moonraker I get this error:
`[NotifyHomeAssistant.py:__init__()] - An invalid Home Assistant Notification Identifier (moonraker) was specified.`

This is my moonraker config.
```[notifier homeassistant]
url: hassio://192.168.0.37:8123/<long_lived_token>?nid=moonraker
events: *
body: "{event_name}"
```

and with this command on terminal it works fine
```apprise --body="test" hassio://192.168.0.37:8123/<long_lived_token>?nid=moonraker```

### Client

Fluidd

### Browser

Firefox

### How to reproduce

Send notification to homeasistant with a Notification ID. See log.

**Comment by pataar** [comment]
Probably the same problem as https://github.com/caronc/apprise/issues/626. Which is fixed in version 1.0.0. I opened a PR (#494) to upgrade apprise.
