### ISSUE TITLE
Klipperscreen error Moonraker_host and Moonraker_port not recognized

### ISSUE THREAD

**Issue by nickeeey** [Arksine/moonraker#498]
### What happened

Hi, i updated my moonraker after a long time and now i got this error on the screen:

https://imgur.com/a/Etw8qRp

This is my config:
[main]
moonraker_host: 127.0.0.1
moonraker_port: 7125

### Client

Mainsail

### Browser

Other or N/A

### How to reproduce

[KlipperScreen.log](https://github.com/Arksine/moonraker/files/9507642/KlipperScreen.log)

**Comment by Arksine** [comment]
This appears to be an issue with KlipperScreen rather than Moonraker.  I would recommend creating an issue in the [KlipperScreen repo](https://github.com/jordanruthe/KlipperScreen).
