### ISSUE TITLE
config_path requirement should not be that it is in home or a subdirectory of home

### ISSUE THREAD

**Issue by expeditioneer** [Arksine/moonraker#51]
Currently the `config_path` must be in **home** or a **subdirectory of home.** This requirement should be relaxed to allow a arbitrary path.

Background: Most Distribution stick to the [FHS](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html). I plan to provide this as a gentoo ebuild and there asubdirectory of **/etc/** should be possible.

**Comment by jordanruthe** [comment]
Check out this previous issue: https://github.com/Arksine/moonraker/issues/45

**Comment by Arksine** [comment]
Indeed this is similar to #45.  I would be willing to make an exception if this functionality is necessary to package moonraker, however I would require more specificity than any subdirectory in `/etc`. For example, I am willing to allow `/etc/moonraker` as an exception.

**Comment by expeditioneer** [comment]
@Arksine feel free to pick a sub directory, - i think `/etc/moonraker` sounds reasonable.

**Comment by Arksine** [comment]
Ok, commit 9a309ff allows directories within `/etc/moonraker`.  You can choose `/etc/moonraker` itself if you want, however I would recommend `/etc/moonraker/config` for the configuration files, that way you could specify `/etc/moonraker/gcode_files` for the gcode files if you like.  That is up to you though.  You simply need to make sure moonraker has permisssion to read/write to this directory.

**Comment by expeditioneer** [comment]
@Arksine Thank you for your fast implementation

**Comment by Arksine** [comment]
Since multiple people have requested a less restrictive directory location I have gone ahead and removed the restriction that folders be located in the HOME directory.  Moonraker will check its permissions on the directory, as long as it has them it will allow it.  The only exception is the system root, which is always prohibited.
