### ISSUE TITLE
Add initial_state for other power devices

### ISSUE THREAD

**Issue by kerry-davis** [Arksine/moonraker#512]
### Is your feature request related to a problem? Please describe

Wanting to to add this option to other power devices, namely a TPLink smartplug so that it's initial state is "on" or "off" just like GPIO devices when moonraker starts and would save time in manually having to switch it on in the power menu.

I bought a TPLink smartplug thinking I could use this for PSU control rather than GPIO saving wiring and having to use a relay etc. - so far I haven't seen a way to do this automatically hence why I'm reaching out.

### Describe the solution you'd like

# moonraker.conf 

[power printer_plug]
type: tplink_smartplug
address: 192.168.1.123
initial_state: on

### Describe alternatives you've considered

Power on G-Code Uploads - kind of works but not the work flow I usually follow to power on a PSU and definitely not as clean as adding an initial state to the plug power settings

**Comment by Arksine** [comment]
FWIW, this was added in commmit 1f1c5904096c8c7b219f407ff25136632032f587.
