### ISSUE TITLE
Moonraker after update stopped working

### ISSUE THREAD

**Issue by markomenino** [Arksine/moonraker#523]
### What happened

After having updated the moonraker it was like in the image.

<a href="https://ibb.co/177dSCg"><img src="https://i.ibb.co/Dzz8qBJ/Moonraker.png" alt="Moonraker" border="0"></a>

I already restarted the raspberry and ran the script: ~/moonraker/scripts/install-moonraker.sh
But it still doesn't open.
With the command sudo journalctl -xe -u moonraker.service in putty this appears:

<a href="https://ibb.co/W3gzzsH"><img src="https://i.ibb.co/mB6yySR/Putty.png" alt="Putty" border="0"></a>

### Client

Fluidd

### Browser

Chrome

### How to reproduce

When opening the fluid

**Comment by user897943** [comment]
I was having errors on the notification bell, which I fixed. From what I can remember, I had to adjust the path to the virtual sd card to my home folder "/home/pi/..." instead of using the "~/...", remove the  old DB because there was a conflict of database folder already exists, and amend the config file to remove some deprecated stuff. Then it worked.

**Comment by Arksine** [comment]
Moonraker has an internal process that corrects the service unit and the config, as mentioned in the announcement that went out last week.  To complete the process you have to enter your password...however if you attempted to reinstall with the install script it likely can't recover.  I have pushed a script that can be used to recover default installations on MainsailOS and FluiddPi.  SSH into the Pi and run the following:

```
cd ~/moonraker
git pull
./scripts/data_path_fix.sh
```

**Comment by tbam** [comment]
> cd ~/moonraker
> git pull
> ./scripts/data_path_fix.sh

I believe this should read (dashes vs underscores in script name):
cd ~/moonraker
git pull
./scripts/data-path-fix.sh

**Comment by Arksine** [comment]
You are correct, thanks tbam.

**Comment by markomenino** [comment]
Problem solved.
Thanks.
