### ISSUE TITLE
Moonraker GCode path received from Klipper does not match expected path

### ISSUE THREAD

**Issue by winniethepinky** [Arksine/moonraker#526]
i tried to load klipper on my 3d printer with fluidd but when i try to load printer.cfg i get this error
![Immagine 2022-10-16 105223](https://user-images.githubusercontent.com/115921575/196026915-c9fb7a6f-b211-43a3-ad06-d8dae8edf424.png)

**Comment by Arksine** [comment]
Please do not create announcements, they are reserved for developer use only.

Check your Klipper configuration (`printer.cfg`) for the virtual sdcard section and change make sure the path is correct.  If not change it.

```ini
[virtual_sdcard]
path: ~/printer_data/gcodes
```
