### ISSUE TITLE
check_sudo_access use lost+found dir

### ISSUE THREAD

**Issue by romanlex** [Arksine/moonraker#529]
### What happened

Hello. I found what `check_sudo_access` from source code use ` lost+found ` for checking.
My system doesn't have this folder. I can't finish install process 
![image](https://user-images.githubusercontent.com/3369304/196662885-d23acf58-d379-4632-b1dc-1270704f8713.png)

See https://github.com/th33xitus/kiauh/issues/244

Source code
![image](https://user-images.githubusercontent.com/3369304/196663021-6018ba24-032f-4e56-9a1a-604e5afc3ab2.png)

`sudo mkdir /lost+found` resolve issue

My system:
![image](https://user-images.githubusercontent.com/3369304/196663577-dde82a2b-34a5-4d1f-b016-c82864260e62.png)

### Client

Mainsail, Fluidd

### Browser

Other or N/A

### How to reproduce

Install moonraker to Ubuntu

**Comment by Arksine** [comment]
Moonraker runs this command to make sure that it can access a folder exclusively owned by root.  The `/lost+found` folder is part of the standard directory hierarchy in linux and should be available in the majority of distros.  It is definitely available in Ubuntu releases maintained by Canonical, I can only assume that the vendor that built your distro decided to leave it out.

That said, I'm fine with changing to `/root`.  Could you check to make sure it is available on your system?

**Comment by romanlex** [comment]
@Arksine yes, `/root` available on my system

**Comment by Arksine** [comment]
Ok, I pushed that fix.  Thanks.
