### ISSUE TITLE
Minor Issue - Configuration Documentation

### ISSUE THREAD

**Issue by bluesheep** [Arksine/moonraker#534]
### What happened

I was following the guide here: [https://github.com/Arksine/moonraker/blob/master/docs/configuration.md#power](url)

My goal was to set up home assistant, then to configure it so that my printer shutdown automatically. I thought I had followed the instructions, but was unsuccessful until I guessed at some unwritten elements.

### Client

Other

### Browser

Other or N/A

### How to reproduce

Line #931 of the file sets up the power device as 'homeassistant_switch'. Line #1131 Sets up the remote method call with a device called 'printer'. This is the label used in the first example (GPIO) but not in subsequent examples.

I had to piece together a few pieces to understand that the remote_method_call was referencing by section label. A simple solution would be to rename the section labels in each example so they all reference 'printer'. A better solution would be to include a TIP that the name needs to match.

### Additional information

None

**Comment by Arksine** [comment]
The documentation has been updated to clarify each parameter in `set_power` remote method, so this should be resolved.
