### ISSUE TITLE
I cannot get GPIO power control working, despite being able to toggle the relay via shell

### ISSUE THREAD

**Issue by Turbine1991** [Arksine/moonraker#545]
### What happened

My device is an Orange PI 4 LTS, running Armbian Ubuntu.

I'm able to manually interact with the relay if I do:
```
echo 33 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio33/direction
echo 1 > /sys/class/gpio/gpio33/value
```

I've read every guide I can get my hands on. Currently it's looking like this:
```
// moonraker.cfg
[button my_button]
type: gpio
pin: gpio33
off_when_shutdown: False

// or
[power printer]
type: gpio
pin: gpio33
off_when_shutdown: True
restart_klipper_when_powered: True
initial_state: off
```

I may get an error when the relay is off:
```
Failed to load power device [power printer]
Error parsing option (pin) from section [power printer]
```

The pin isn't being exported in /sys/class/gpio

I've dealt with GPIO many times before, but I've never had so much trouble.

### Client

Mainsail

### Browser

Chrome

### How to reproduce

--

**Comment by Arksine** [comment]
Please attach `moonraker.log` reproducing the issue.  I suspect this is a duplicate of #249.  Moonraker does not use sysfs to toggle gpio, it uses libgpiod.  Your distro must be configured to give the user the correct permissions.
