### ISSUE TITLE
Cannot install new moonraker

### ISSUE THREAD

**Issue by ymanyin** [Arksine/moonraker#567]
### What happened

Cannot install Moonraker.
Failed on kiauh installation.
Then I tried manually install by:
cd ~/moonraker/scripts
./install-moonraker.sh
Installation stops always at creating python virtual environment
I did the same installation around 10days ago, didnt have any problem.
Any help? Thanks in advance!

### Client

Mainsail
Orange Pi
Armbian 21.05.6 Buster with Linux 5.10.43-sunxi

### Browser

Chrome

### How to reproduce

Reproduce every time runs
cd ~/moonraker/scripts
./install-moonraker.sh

###### Installing python virtual environment...
Collecting tornado==6.2.0
  Using cached tornado-6.2.tar.gz (504 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pyserial==3.4
  Using cached pyserial-3.4-py2.py3-none-any.whl (193 kB)
Collecting pyserial-asyncio==0.6
  Using cached pyserial_asyncio-0.6-py3-none-any.whl (7.6 kB)
Collecting pillow==9.3.0
  Downloading Pillow-9.3.0.tar.gz (50.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 50.2/50.4 MB 4.1 MB/s eta 0:00:01./install-moonraker.sh: line 49:  1978 Killed                  ${PYTHONDIR}/bin/pip install -r ${SRCDIR}/scripts/moonraker-requirements.txt
![Untitled](https://user-images.githubusercontent.com/56856272/207772736-e88b425e-aa1b-4722-b4a6-b89879c97691.png)

**Comment by ymanyin** [comment]
Tried all day, it always stop at downloading Pillow-9.3.0

I also tried to manually install Pillow-9.3.0. It failed every time.
What can I do to resolve the situation? Thanks in advance.

  Downloading Pillow-9.3.0.tar.gz (50.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 50.3/50.4 MB 4.1 MB/s eta 0:00:01Killed

**Comment by Arksine** [comment]
Unfortunately this appears to be some kind of OS issue and there is little I can do.  Hopefully in the time since you created this you were able to resolve it with assistance from the discord or discourse.  Perhaps an update to Armbian is necessary to fix the issue.
