### ISSUE TITLE
Simplify3D V5 Support

### ISSUE THREAD

**Issue by wuast94** [Arksine/moonraker#571]
### Is your feature request related to a problem? Please describe

Metadata isnt read or just not showed by mainsail 

### Describe the solution you'd like

Add Metadata support

### Additional information

here is an example gcode: 
[Support_test.zip](https://github.com/Arksine/moonraker/files/10255003/Support_test.zip)

If you need more infos just ask :)

**Comment by cotepat** [comment]
It seems that S3D changed the comments in code containing this metadata. Here is a workaround (that works perfectly) to put in S3D post processing script : 

{STRIP(";   postProcessingScript")}
{REPLACE("Build Time" "Build time")} 
{REPLACE("Material Weight" "Plastic weight")} 
{REPLACE("Material Length" "Filament length")}
{APPEND("; extruderDiameter,0.60\n")}
curl -k -H "X-Api-Key:x" -F "select=false" -F "print=false" -F "file=@[output_filepath]" "http://192.168.0.xxx/api/files/local"
