### ISSUE TITLE
[multi instances] GCode path received from Klipper does not match expected location

### ISSUE THREAD

**Issue by baronvonk** [Arksine/moonraker#582]
### What happened

Hi, 

like a few other people I got this warning message after update:

**_GCode path received from Klipper does not match expected location.
Received: ‘/home/pi/gcode_files’
Expected: ‘/home/pi/printer_1_data/gcodes’_**

The thing is, I run 3 instances (klipper+moonraker) on the same pi to control 3 different printers. Installed with KIAUH

I tried editing the [virtual_sdcard] section of each config files (mainsail.cfg and printer.cfg) to point to ~/home/pi/gcodes but the only thing that changed is that I don't get this warning from moonraker anymore. But I still can't acces my gcodes.

I understand that moonraker wants me to put the gcodes folder in printer_1_data, printer_2_data and printer_3_data, but it's not really an option since it would take 3x times the space and 3x times longer to do at each gcode. Is there a way to route each instances to the same folder in ~/home/pi ?

Thanks for your time in advance

### Client

Mainsail

### Browser

Firefox

### How to reproduce

Install 3 instances of klipper and 3 instance of moonraker using KIAUH.

**Comment by baronvonk** [comment]
Solved: command ln -s
ln -s /home/pi/gcode_files /home/pi/printer_x_data/gcodes
makes a shortcut directing to the main gcode folder. Printer.cfg can still have the required path for moonraker, and I get my centralized folder.

**Comment by Mrmad1966** [comment]
> Solved: command ln -s ln -s /home/pi/gcode_files /home/pi/printer_x_data/gcodes makes a shortcut directing to the main gcode folder. Printer.cfg can still have the required path for moonraker, and I get my centralized folder.

Thanks hero....................been looking for this answer for a loooooongtime
