### ISSUE TITLE
E: Unable to locate package python3-libgpiod on AMD64 ubuntu 18.04

### ISSUE THREAD

**Issue by anand-010** [Arksine/moonraker#585]
### What happened

I have updated python from 3.6 to 3.10 after i've tried to install moonracker and i've got error E: Unable to locate package python3-libgpiod.

### Client

Mainsail, Fluidd

### Browser

Chrome

### How to reproduce

Try to install on non arm debian.

**Comment by Arksine** [comment]
Ubuntu 18.04 is likely too old to install Moonraker via the default install script, as its intended for Debian 9 and above (Ubuntu 20.04 should work).  You will likely need to create your own install script, you should be able to remove the libgpiod dependency if you don't intend to use the `power` component.

**Comment by manic101** [comment]
Having the same problem with Ubuntu 18.04 
I am running it in an old laptop that is 32 bit, so need to use this version of ubuntu

**Comment by Arksine** [comment]
[Debian Bullseye](https://www.debian.org/releases/bullseye/debian-installer/) has an i386 installer.  As mentioned, Ubuntu 18.04 ships without dependencies Moonraker requires.  You are free to try to install on that machine, however it is likely going to be nothing but trouble and is unsupported.

**Comment by Arksine** [comment]
As this discussion seems to have concluded I am going to close this.
