### ISSUE TITLE
klippy.log empty

### ISSUE THREAD

**Issue by legend069** [Arksine/moonraker#594]
### What happened

using the fluidd web GUI klippy.log is empty, been like that for a while when ever i tried to look at it.

loaded up winscp to take a look and noticed something funny has happened to the log numbering.

![image](https://user-images.githubusercontent.com/40685552/213933798-0e73a7ae-1ecb-4eac-9afe-4d8ab100c85d.png)

### Client

Fluidd

### Browser

Firefox

### How to reproduce

several rebooting, and still don't get a log file.

if i open klippy.log1 it looks like it should and has a correct time/date stamp with it.

guess it all started form https://github.com/Arksine/moonraker/issues/516

**Comment by Arksine** [comment]
Moonraker itself should not modify the file names.  Without `moonraker.log` I can't diagnose this, however from the screenshot it appears that some other software is modifying the log files and possibly compressing them.

**Comment by legend069** [comment]
sorry, thought i uploaded the logfile.
[moonraker(12).log](https://github.com/Arksine/moonraker/files/10495447/moonraker.12.log)

the only other software i think i have installed i samba,
otherwise it's just the standard klipper/fluidd stuff.

**Comment by Arksine** [comment]
There isn't anything in the log that stands out other than this:
```
Unsafe Shutdown Count: 273
```
When you remove power from the Pi without safely shutting down the OS then strange things can happen, usually as a result of file system corruption.   That said, something on your machine is renaming the log files (see the `klippy.log.1`, `moonraker.log.1`).  There are also compressed files (see the `.xz` files).  If you are using a specific distrubution (such as FluiddPi) then you might want to see assistance in the Fluidd Discord, GitHub, etc.

**Comment by legend069** [comment]
that doesn't explain how at the moment klipper is currently writing logs to the wrong file though?

**Comment by legend069** [comment]
> 

i'll close this issue now, i've wiped the card and started again.
