### ISSUE TITLE
[Feature Request] Turn off power device on MCU Shutdown

### ISSUE THREAD

**Issue by pheonix3330** [Arksine/moonraker#60]
Would it be possible to allow us to turn off a power device when there is an MCU shutdown? It would be useful if there was a thermal runaway event for Moonraker to kill power to the printer.

**Comment by Arksine** [comment]
This was added in commit 222f0c4.  You can set the `off_when_shutdown` option to true to have your device power down after a shutdown is detected.

**Comment by pheonix3330** [comment]
Thanks Arksine!
