### ISSUE TITLE
after loading history - there are already 2 selected jobs

### ISSUE THREAD

**Issue by fused3dprints** [Arksine/moonraker#611]
### What happened

![image](https://user-images.githubusercontent.com/112317534/218448221-5e23fc73-2e22-4e56-9102-18daa70e1a5d.png)

I just noticed that i automatically have 2 selected jobs whenever i load history tab but the details are now shown.
I can export the jobs (via CSV) and can confirm these are old jobs i printed.
Tried to query via history api and they are not showing. 

### Client

Mainsail

### Browser

Chrome, Microsoft Edge

### How to reproduce

just need to open the history tab

### Additional information

[print_history.csv](https://github.com/Arksine/moonraker/files/10721775/print_history.csv)
[API_out.txt](https://github.com/Arksine/moonraker/files/10721794/API_out.txt)
[moonraker.log](https://github.com/Arksine/moonraker/files/10721883/moonraker.log)

attaching the CSV file and API history output for reference.
i found the following in the moonraker.log -- but not sure if these are the 2 problematic jobs

                Invalid job uid: 0000E5
                Invalid job uid: 000103

**Comment by fused3dprints** [comment]
Thanks for the quick response. 
I'm really new to this and will try to open a BUG report in the mainsail github.

**Comment by Arksine** [comment]
I am going to close this as it seems like the discussion has concluded.
