### ISSUE TITLE
updated and now nothing

### ISSUE THREAD

**Issue by B1ack0u1** [Arksine/moonraker#627]
### What happened

updated via mainsail and now it wont connect
![moonraker](https://user-images.githubusercontent.com/64473818/222986715-ae45da6c-797b-4c91-81a6-9dea1e833a15.jpg)

### Client

Mainsail

### Browser

Chrome

### How to reproduce

just tried to update

### Additional information

[moonraker.log](https://github.com/Arksine/moonraker/files/10892992/moonraker.log)

**Comment by Arksine** [comment]
Your repo is corrupt, Moonraker can't start because the source is garbled.  You'll need to re-clone, ssh into the device and do the following:

```
sudo service moonraker stop
cd ~
rm -rf moonraker
git clone https://github.com/Arksine/moonraker.git
sudo service moonraker start
```

FWIW, your log shows the following:
```
2023-03-05 20:45:42,674 [server.py:add_log_rollover_item()] - Unsafe Shutdown Count: 685
```
Powering off your host without safely shutting down is the leading cause of repo/file system corruption.

**Comment by B1ack0u1** [comment]
hi, thanks for your reply.
it hasnt resolved my issue so ill probably try a reinstall of klipper thanks
stu

**Comment by Arksine** [comment]
This discussion seems to have concluded, so I am going to close this.
