### ISSUE TITLE
http api

### ISSUE THREAD

**Issue by celiu12345** [Arksine/moonraker#629]
### What happened

I need to call the api provided by moonraker through http to obtain coordinates, but according to the information given in the document, I try to obtain coordinates in this way:
    http://192.168.128.19:7125/printer/gcode/script?script=M114
    http://192.168.128.19:7125/printer/gcode/script?script=get_position
    http://192.168.128.19:7125/printer/gcode/script?script=GET_POSITION
Only return：{ "result": "ok" }

Oh, I have tried both get and post, and still only the above results are returned, but **script=G28** is normal, and the motor starts to rotate

I know that this can be achieved through WebSocket, but it is too troublesome for me, so I want to determine whether it can be achieved through http api.

I have been troubled by this problem for many days. I need help very much. Thank you very much

### Client

MoonCord, Other

### Browser

Chrome, Other or N/A

### How to reproduce

post or get
http://192.168.128.19:7125/printer/gcode/script?script=M114
http://192.168.128.19:7125/printer/gcode/script?script=get_position
http://192.168.128.19:7125/printer/gcode/script?script=GET_POSITION

return：
{
	"result": "ok"
}

**Comment by Arksine** [comment]
The websocket is required to receive gcode responses, as Klipper sends them asynchronously.  That said, parsing gcode responses is not the ideal way to get printer status even when using the websocket.  The [query API](https://moonraker.readthedocs.io/en/latest/web_api/#query-printer-object-status) can be used to query printer objects and get state.
