### ISSUE TITLE
Mistake in documentation? / Home Assistant Switch

### ISSUE THREAD

**Issue by wassereimer86** [Arksine/moonraker#633]
### What happened

I tried getting a home assistant power switch to run, but it wouldn't. After I replaced the device ID with the entity ID it's working. Is that a mistake in the documentation?

### Client

Mainsail

### Browser

Chrome

### How to reproduce

Setup a home assistant switch.

**Comment by hmortensen83** [comment]
The commit eff0901 solved the issue.
