### ISSUE TITLE
Cannot address GPIO pin on Odroid C2 running Armbian 23.02.1

### ISSUE THREAD

**Issue by mikebzh44** [Arksine/moonraker#638]
### What happened

Hello.

I'm trying to power on / off my printer using a relay board wired to my Odroid C2.

chipset is detected : 

$ gpiodetect
gpiochip0 [aobus-banks] (15 lines)
gpiochip1 [periphs-banks] (119 lines)

and GPIO are listed : 

$ gpioinfo gpiochip1|grep J2
        line  78: "J2 Header Pin35" unused input active-high
        line  82: "J2 Header Pin36" unused input active-high
        line  83: "J2 Header Pin31" unused input active-high
        line  88: "J2 Header Pin32" unused input active-high
        line  89: "J2 Header Pin26" unused input active-high
        line  92: "J2 Header Pin29" unused input active-high
        line  93: "J2 Header Pin24" unused input active-high
        line  94: "J2 Header Pin23" unused input active-high
        line  95: "J2 Header Pin22" unused input active-high
        line  96: "J2 Header Pin21" unused input active-high
        line  97: "J2 Header Pin18" unused input active-high
        line  98: "J2 Header Pin33" unused input active-high
        line  99: "J2 Header Pin19" unused input active-high
        line 100: "J2 Header Pin16" unused input active-high
        line 101: "J2 Header Pin15" unused input active-high
        line 102: "J2 Header Pin12" unused input active-high
        line 103: "J2 Header Pin13" unused input active-high
        line 104: "J2 Header Pin8" unused input active-high
        line 105: "J2 Header Pin10" unused input active-high
        line 111: "J2 Header Pin11" unused input active-high
        line 113: "J2 Header Pin7" unused input active-high

I can trigger the relay using this command lines : 

gpioset --bias=pull-up gpiochip1 113=0
gpioset --bias=pull-up gpiochip1 113=1

But I can't define a new entry in moonraker.conf : 

[power printer]
type: gpio
pin: gpiochip1/113
off_when_shutdown: True
initial_state: off

I have tried several ways because I have rebuild /boot/dtb-6.1.11-meson64/amlogic/meson-gxbb-odroidc2.dtb to rename GPIO pins (at least when using gpioingo command line) : 
J2_Header_Pinx
GPIOx

I also try using GPIOX.21 given by HardKernel : https://wiki.odroid.com/odroid-c2/hardware/expansion_connectors

But I'm always facing the same error : 

2023-03-28 16:54:38,088 [server.py:add_warning()] - Failed to load power device [power printer]
Error parsing option (pin) from section [power printer]

### Client

Mainsail

### Browser

Chrome

### How to reproduce

Install moonraker on a Odroid C2 board

**Comment by Arksine** [comment]
Without `moonraker.log` there isn't much to go on, but it appears that this is the case of misconfiguring Moonraker.  The `pin` option should be in the format of `pin: gpiochip1/gpio113`.

That said, I can't provide real support for SBCs outside of the Raspberry Pi.  When something doesn't work it is commonly a Kernel issue or some other problem with the distro.

**Comment by Arksine** [comment]
This discussion seems to have concluded, so I am going to close this.

**Comment by Arakon** [comment]
Since I was facing the same issue, I figured I'd leave this here for others. I hope I got all the steps covered, since I was messing around with various different solutions.
Note that I named my user "pi" on the Odroid too, for simplicity between different printers.

```
sudo groupadd gpio
sudo usermod -a -G gpio pi
sudo chgrp gpio /dev/gpiochip*
sudo chmod g+rw /dev/gpiochip*
```

And then in moonraker.conf:
"gpio102" equals pin 12 on the GPIO header, in this case. See the list above for reference.
Depending on your type of relay, you may have to add a "!" in front of the gpiochip1 for the toggle to be the right way around.

```
[power printer]
type: gpio
pin: gpiochip1/gpio102
off_when_shutdown: True
restart_klipper_when_powered: true
initial_state: off
```
