### ISSUE TITLE
Object height is reported taller than it's actual size.

### ISSUE THREAD

**Issue by jurisv** [Arksine/moonraker#639]
### What happened

Possible regression or bug. 
The reported object height displayed is 0.20 mm taller than actual object. In the example above the brace is 20mm, not 20.20...
This overhead is consistent with the first layer height. (if the first layer height is 0.25, then the object will be taller by that number)
<img width="1191" alt="wrong height" src="https://user-images.githubusercontent.com/643535/228377004-1c47114a-48e4-4c08-b9a1-2bd40206fb92.png">

### Client

Mainsail

### Browser

Chrome

### How to reproduce

Slice anything and upload the g-code, then check the displayed values.

**Comment by Arksine** [comment]
This isn't a bug, but instead a limitation of the slicer.  It does not report the actual object height so the metadata processor attempts to estimate it by parsing the highest Z value out of the gcode file.  Depending on the slicer and how its configured this can result in an object height that is slightly off.

**Comment by duerk-de** [comment]
See here: [https://github.com/SoftFever/OrcaSlicer/issues/1703#issuecomment-1674851489](https://github.com/SoftFever/OrcaSlicer/issues/1703#issuecomment-1674851489)

Moonraker seems to need special gcode to calculate the height correctly.
