### ISSUE TITLE
MQTT Connection ERROR

### ISSUE THREAD

**Issue by smilecaozheng** [Arksine/moonraker#648]
### What happened

Due to my MQTT server was started by Docker, Whenever I start Moonraker, the MQTT server has not yet started. So It reported an error. Can I set the [mqtt] option in moonrake.config ,To wait for the MQTT server to start successfully? If not, can we join in the future? 

Ps: I noticed the following code in the Python code.

Error log:
![image](https://user-images.githubusercontent.com/23375339/235281519-24a2f17e-7889-426e-8493-63c77c9e0ef7.png)

### Client

Fluidd

### Browser

Microsoft Edge

### How to reproduce

Startup sequence：
moonraker[mqtt client] -> docker[mqtt server] -> MQTT Connection Error

In this sequence, it can be seen from the server that another device is connected, but Moonraker is not connected.
![image](https://user-images.githubusercontent.com/23375339/235282811-5a49c7b0-b035-43a8-afe2-dffd055cdb60.png)

->Restart moonrake：
It can be connected after restarted.
![image](https://user-images.githubusercontent.com/23375339/235282843-b60d38e7-f9cf-48de-8695-2c99e48868c2.png)

**Comment by Arksine** [comment]
Moonraker should attempt to reconnect if the initial connection fails.  The full `moonraker.log` needs to be attached for me to diagnose further.

**Comment by smilecaozheng** [comment]
[moonraker.log](https://github.com/Arksine/moonraker/files/11440965/moonraker.log)
Attach log file

**Comment by Arksine** [comment]
A few things I can determine from the log:
1) It appears that Moonraker's source has been modified.  It's difficult for me to provide reliable feedback on modified code as the modifications themselves can be the source of the issue.
2) The traceback reported in the OP isn't reproduced in the log attached.
3) It does appear that on some attempts that the client is connecting, however the broker isn't responding.  This issue would be outside of Moonraker's scope.

**Comment by smilecaozheng** [comment]
Here's an explanation：
1.Indeed, this has added some of my own components. I will remove this and resend the log.
The current state should be uncontaminated.
![image](https://github.com/Arksine/moonraker/assets/23375339/c5a556e3-cde4-456f-a21e-676aaf05fd68)

2.Will be retested in sequence.
3.This part doesn't seem to be understood, it's like this: when Moonraker starts, the broker doesn't start, it only starts about 2 minutes after Moonraker starts. Does this mean that if Moonraker starts without discovering the broker, it will throw a timeout exception and will not attempt to connect again.

(1)
moonraker[mqtt client] ->At this time, an error should have been reported

[moonraker (1).log](https://github.com/Arksine/moonraker/files/11452454/moonraker.1.log)

docker[mqtt server] -> another device is connected, but Moonraker is not connected.
![image](https://github.com/Arksine/moonraker/assets/23375339/45de4a1e-9d30-4e4c-9021-47798aa2586a)
Please ignore Chinese

(2)
moonraker[mqtt client] restart
[moonraker (2).log](https://github.com/Arksine/moonraker/files/11452479/moonraker.2.log)

![image](https://github.com/Arksine/moonraker/assets/23375339/f6441ae6-7268-4e9d-be6c-6d4dfa2621fb)
MzEwNjA4MTU0NDEzMDU1N ：This device is a klipper device

**Comment by smilecaozheng** [comment]
Solution: Install the mqtt server directly without using Docker
