### ISSUE TITLE
Virtual_sdcard.file_position does not return integer

### ISSUE THREAD

**Issue by Clon1998** [Arksine/moonraker#673]
### What happened

Recently some users of Mobileraker started to see a weired parsing bug for the virtual_sdcard.
I tracked it down to the file_position field, which returns a double (0.0) if it is zero otherwise it returns an integer as documented in the docs.

> file_position: The current file position in bytes. This will always be an integer value

### Client

MobileRaker

### Browser

Other or N/A

### How to reproduce

For me it was sufficient to start a print and cancel it. The query endpoint for virtual SdCard always returns 0.0 instead of an integer value afterwards.

If the PI/Klipper was freshly restated it returned the integer 0 value as expected.

**Comment by Arksine** [comment]
Thanks.  This is either an error in Moonraker's documentation or a bug in Klipper.  I have submitted a PR to resolve it in Klipper, linked above.  I suspect there won't be any issue with its acceptance, however if it is not accepted I'll update Moonraker's documentation to state that this value can be a float or an integer.
