### ISSUE TITLE
Unable to upload files from slicers

### ISSUE THREAD

**Issue by Myklt8** [Arksine/moonraker#681]
### What happened

Cura and Orca Slicers do not upload to moonraker, they time out
I reimaged my laptop that runs Klipper, updated the IP address, and added the port and they still won't upload
Times out after a very long time. I am seeing this a lot on FB. 

### Client

Mainsail

### Browser

Firefox

### How to reproduce

Just slice any file and try to upload

### Additional information

[moonraker.log](https://github.com/Arksine/moonraker/files/11984664/moonraker.log)

**Comment by Arksine** [comment]
According to the log Moonraker isn't receiving the request.  Based the description of your issue it sounds like your laptop has port 7125 firewalled.   You'll need to open up the port if you want to access Moonraker directly from another machine on your network.

If you have nginx or another reverse proxy running you can likely test this by removing the port in your slicer.  The thing to keep in mind with nginx is that you need to make sure the nginx timeout isn't too short, as per #556.

**Comment by Myklt8** [comment]
That was it, Thank you!!!!
   Michael Tate   

    On Friday, July 7, 2023 at 01:54:11 PM CDT, Eric Callahan ***@***.***> wrote:  
 
 


According to the log Moonraker isn't receiving the request. Based the description of your issue it sounds like your laptop has port 7125 firewalled. You'll need to open up the port if you want to access Moonraker directly from another machine on your network.

If you have nginx or another reverse proxy running you can likely test this by removing the port in your slicer. The thing to keep in mind with nginx is that you need to make sure the nginx timeout isn't too short, as per #556.

**Comment by Arksine** [comment]
Good to hear, thanks.

**Comment by Myklt8** [comment]
Actually started again, even with the port open Tried different slicers with the same result 

Sent from Yahoo Mail on Android 
 
  On Sun, Jul 9, 2023 at 5:22 AM, Eric ***@***.***> wrote:   


Closed #681 as completed.

**Comment by Myklt8** [comment]
I disabled the firewall completely and all is good again 

Sent from Yahoo Mail on Android 
 
  On Sun, Jul 9, 2023 at 6:14 AM, Michael ***@***.***> wrote:   Actually started again, even with the port open Tried different slicers with the same result 

Sent from Yahoo Mail on Android 
 
  On Sun, Jul 9, 2023 at 5:22 AM, Eric ***@***.***> wrote:   


Closed #681 as completed.
