### ISSUE TITLE
Tasmota Configuration 

### ISSUE THREAD

**Issue by stefan63** [Arksine/moonraker#693]
### What happened

adress Tasmota1  Do not work (SSID/Hostname)
adress: 102.168.1.11  WORKS!

### Client

Fluidd

### Browser

Chrome

### How to reproduce

Simply try to enter Hostname of Tasmota device insted of IP and se if it works.

### Additional information

It did work in the past but I can not remember in wich version :(

**Comment by stefan63** [comment]
Thank you for your answer I will look in to it, and I bet you are right it
something with my local DNS.
Love your work, kind regards/Stefan

Den tors 27 juli 2023 kl 18:08 skrev Eric Callahan ***@***.***

**Comment by Arksine** [comment]
As this discussion seems to have concluded I am going to close this.  Thanks.
