### ISSUE TITLE
moonraker.service has entered the 'failed' state with result 'exit-code'.

### ISSUE THREAD

**Issue by NikkiB422** [Arksine/moonraker#737]
### What happened

Oct 29 23:08:23 mkspi python[3825]: moonraker.confighelper.ConfigError: Configuration File Not Found: '/home/mks/klipper_config/moonraker.conf''
Oct 29 23:08:23 mkspi python[3825]: [server.py:main()] - Server Shutdown
Oct 29 23:08:23 mkspi systemd[1]: moonraker.service: Main process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- An ExecStart= process belonging to unit moonraker.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 1.
Oct 29 23:08:23 mkspi systemd[1]: moonraker.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit moonraker.service has entered the 'failed' state with result 'exit-code'.

### Client

Mainsail, KlipperScreen

### Browser

Other or N/A

### How to reproduce

mks@mkspi:~/moonraker$ sudo journalctl -xe -u moonraker
Oct 29 23:08:23 mkspi python[3825]:     config = confighelper.get_configuration(
Oct 29 23:08:23 mkspi python[3825]:   File "/home/mks/moonraker/moonraker/config
Oct 29 23:08:23 mkspi python[3825]:     source.read_file(start_path)
Oct 29 23:08:23 mkspi python[3825]:   File "/home/mks/moonraker/moonraker/config
Oct 29 23:08:23 mkspi python[3825]:     self._parse_file(main_conf, [])
Oct 29 23:08:23 mkspi python[3825]:   File "/home/mks/moonraker/moonraker/config
Oct 29 23:08:23 mkspi python[3825]:     f"Configuration File Not Found: '{file_p
Oct 29 23:08:23 mkspi python[3825]: moonraker.confighelper.ConfigError: Configur
Oct 29 23:08:23 mkspi python[3825]: [server.py:main()] - Server Shutdown
Oct 29 23:08:23 mkspi systemd[1]: moonraker.service: Main process exited, code=e
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- An ExecStart= process belonging to unit moonraker.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 1.
Oct 29 23:08:23 mkspi systemd[1]: moonraker.service: Failed with result 'exit-co
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit moonraker.service has entered the 'failed' state with result 'exit-c
lines 1715-1737/1737 (END)
Oct 29 23:08:23 mkspi python[3825]:     config = confighelper.get_configuration(self, self.app_args)
Oct 29 23:08:23 mkspi python[3825]:   File "/home/mks/moonraker/moonraker/confighelper.py", line 1051, in get_configuration
Oct 29 23:08:23 mkspi python[3825]:     source.read_file(start_path)
Oct 29 23:08:23 mkspi python[3825]:   File "/home/mks/moonraker/moonraker/confighelper.py", line 1039, in read_file
Oct 29 23:08:23 mkspi python[3825]:     self._parse_file(main_conf, [])
Oct 29 23:08:23 mkspi python[3825]:   File "/home/mks/moonraker/moonraker/confighelper.py", line 1025, in _parse_file
Oct 29 23:08:23 mkspi python[3825]:     f"Configuration File Not Found: '{file_path}''") from e
Oct 29 23:08:23 mkspi python[3825]: moonraker.confighelper.ConfigError: Configuration File Not Found: '/home/mks/klipper_config/moonraker.conf''
Oct 29 23:08:23 mkspi python[3825]: [server.py:main()] - Server Shutdown
Oct 29 23:08:23 mkspi systemd[1]: moonraker.service: Main process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- An ExecStart= process belonging to unit moonraker.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 1.
Oct 29 23:08:23 mkspi systemd[1]: moonraker.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit moonraker.service has entered the 'failed' state with result 'exit-code'.

**Comment by Arksine** [comment]
As no one has been able to provide further feedback I'm going to close this.  If you are still having issues I recommend asking for assistance on the Klipper Discourse.
