### ISSUE TITLE
Feature request: Power off certain minutes after print finished

### ISSUE THREAD

**Issue by oeijoenj** [Arksine/moonraker#74]
Hi,

Is it possible to power off printer certain minutes after print finished using gpio ?
thanks

jonathan

**Comment by Arksine** [comment]
You could set up a [delayed_gcode] that powers off your printer, to be called in your print's end gcode.  Assuming the gpio is named "printer", you could add the following to printer.cfg:
```
[gcode_macro POWER_OFF_PRINTER]
gcode:
  {action_call_remote_method("set_device_power",
                             device="printer",
                             state="off")}

[delayed_gcode delayed_printer_off]
initial_duration: 0.
gcode:
    POWER_OFF_PRINTER
```

Then in your  end gcode add something like this:
```
UPDATE_DELAYED_GCODE ID=delayed_printer_off DURATION=120
```
That would power down your printer 2 minutes after the print completes.

**Comment by oeijoenj** [comment]
Hi Arksine,

Thanks for your response.
Actually i use this script in moonraker.conf 

`[power printer]
type: gpio
pin: !gpio22
off_when_shutdown: False
initial_state: on`

Any idea how to implement delayed gcode ? I dont know much how to do scripting.
Thanks so much.


> You could set up a [delayed_gcode] that powers off your printer, to be called in your print's end gcode. Assuming the gpio is named "printer", you could add the following to printer.cfg:
> 
> ```
> [gcode_macro POWER_OFF_PRINTER]
> gcode:
>   {action_call_remote_method("set_device_power",
>                              device="printer",
>                              state="off")}
> 
> [delayed_gcode delayed_printer_off]
> initial_duration: 0.
> gcode:
>     POWER_OFF_PRINTER
> ```
> 
> Then in your end gcode add something like this:
> 
> ```
> UPDATE_DELAYED_GCODE ID=delayed_printer_off DURATION=120
> ```
> 
> That would power down your printer 2 minutes after the print completes.

**Comment by Arksine** [comment]
My previous comment outlined how to implement the delayed gcode in printer.cfg.

**Comment by oeijoenj** [comment]
Got it.
Just did the change and works as expected.
Thanks so much.


> My previous comment outlined how to implement the delayed gcode in printer.cfg.
