### ISSUE TITLE
G28 | Message: Homing failed due to printer shutdown | MCU 'mcu' shutdown: Timer too close

### ISSUE THREAD

**Issue by b1alek** [Arksine/moonraker#786]
### What happened

Tried to make clean install on fresh SDHC card  attached with printer, however issiue persist.

No matter if I;ll try to home using Fluidd or Mainsail - both homing operations makes MCU shutdown

It seems not to be related with bananapi usage
# iostat -h
Linux 6.1.63-current-sunxi (bananapi)   01/09/2024      _armv7l_        (2 CPU)

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          18.6%    0.1%   11.0%    2.5%    0.0%   67.8%

      tps    kB_read/s    kB_wrtn/s    kB_dscd/s    kB_read    kB_wrtn    kB_dscd Device
     8.89        94.0k       521.5k         1.1M     504.3M       2.7G       5.7G mmcblk0
     3.57         2.6k        11.7k         0.0k      13.8M      62.7M       0.0k zram0
     0.30         0.2k         1.8k         0.0k     944.0k       9.8M       0.0k zram1

in klipper there is relevant

Receive: 99 3719.826001 3719.821624 12: seq: 12, shutdown clock=2506874554 static_string_id=Timer too close
Transition to shutdown state: MCU 'mcu' shutdown: Timer too close

### Client

Mainsail, Fluidd

### Browser

Chrome

### How to reproduce

bananapi A20

### Additional information

G28 Z [moonraker G28 issiue.log](https://github.com/Arksine/moonraker/files/13872597/moonraker.G28.issiue.log)
G28 Z [klippy G28.log](https://github.com/Arksine/moonraker/files/13872617/klippy.G28.log)

G28 X [moonraker (2).log](https://github.com/Arksine/moonraker/files/13872598/moonraker.2.log)
[moonraker (1).log](https://github.com/Arksine/moonraker/files/13872629/moonraker.1.log)
[klippy (11).log](https://github.com/Arksine/moonraker/files/13872630/klippy.11.log)

**Comment by Arksine** [comment]
This appears to be an issue with Klipper.  I would suggest using the [Klipper Discourse](https://klipper.discourse.group/t/timer-too-close/6634) for assistance.

**Comment by Arksine** [comment]
As no one has been able to provide further feedback I'm going to close this.  If you are still having issues I recommend asking for assistance on the Klipper Discourse.
