### ISSUE TITLE
[Enhancement] Add docs link to the repository metadata

### ISSUE THREAD

**Issue by HumbleDeer** [Arksine/moonraker#796]
### Is your feature request related to a problem? Please describe

The repository lacks a quick link to the documentation in the about/sidebar.

This is especially noticeable to those browsing on a mobile browser, as the About section is the first thing to apear topmost of the page. Example below:

![repo_about-section](https://github.com/Arksine/moonraker/assets/16231288/219d4c8b-932f-4fc8-a92f-fea9757279d2)

### Describe the solution you'd like

Adding the website is fairly simple and a trivial task (once you know about it). 

Steps to accomplish this:

1. Locate the settings icon on the About section
![repo_about-gear](https://github.com/Arksine/moonraker/assets/16231288/20fd6ad7-10b2-4482-80ae-14ac98deb165)
2. Fill in the website URL and save the changes
![moonraker_repo_edit-details](https://github.com/Arksine/moonraker/assets/16231288/1b197d4a-dec7-494f-9ca6-08178e6213ee)
3. Admire your relentless dedication to providing for the people
![moonraker_about-site-mobile](https://github.com/Arksine/moonraker/assets/16231288/fbd9105e-ee03-4121-947b-297734eb4ce0)
![moonraker_about-site-desktop](https://github.com/Arksine/moonraker/assets/16231288/788deb67-9b5f-430e-8e30-53228e500262)

### Additional information

This is optional, and merely an enhancement for SEO. The suggestion comes out of my own experience in managing repositories for projects, and experience with what makes a difference in QOL and ease of use. 

If this does not follow your procedure or standards, feel free to close this PR.

**Comment by Arksine** [comment]
Done.  Thanks for the tip.
