### ISSUE TITLE
Generic HTTP request power on printer

### ISSUE THREAD

**Issue by oRudi07** [Arksine/moonraker#805]
### What happened

Hi, I tried to configure the power option in Mainsail to power my printer on/off.
This is the config:
[power printer]
type: http
on_url: http://192.168.1.20:8087/set/zwave2.0.Node_003.Binary_Switch.targetValue?value=true
off_url: http://192.168.1.20:8087/set/zwave2.0.Node_003.Binary_Switch.targetValue?value=false
status_url: http://192.168.1.20:8087/getPlainValue/zwave2.0.Node_003.Binary_Switch.currentValue

The Switch is configured in ioBroker, but i cannot control the switch with this configuration.
What do i have to put in the response_template and request_template to get it work?

### Client

Mainsail

### Browser

Chrome

### How to reproduce

no

**Comment by Arksine** [comment]
Unfortunately it appears that no one was able to assist with your specific help request.  If you still need assistance I would recommend the Klipper Discord or Discourse, as you may get a more prompt reply.
