### ISSUE TITLE
Feature Request: UFP parsing/unzipping from filesystem

### ISSUE THREAD

**Issue by Rejdukien** [Arksine/moonraker#81]
Currently UFP files are being parsed only on file upload. However, sometimes it might be more practical to just use good old samba network shares to copy files to the raspberry - such as currently curas octoprint upload plugin using a different api version than implemented in moonraker (or atleast that's the current situation, if I understood correctly).

Therefore I'd like to propose running any detected .ufp file in the gcodes folder through the same method as used on file upload - Unzipping the UFP, extracting thumbs/gcode from it and discarding the ufp.

https://github.com/Arksine/moonraker/blob/943b78195bc44b67206246f2e5b6af7bba5f407d/moonraker/plugins/file_manager.py#L421

I've had semi-success by just naively modifying the _list_directory method as follows, but obviously that's a rather dirty solution.

```python
    def _list_directory(self, path, is_extended=False):
        if not os.path.isdir(path):
            raise self.server.error(
                f"Directory does not exist ({path})")
        flist = {'dirs': [], 'files': []}
        # Addition 1 START
        dirty = False
        # Addition 1 END
        for fname in os.listdir(path):
            full_path = os.path.join(path, fname)
            if not os.path.exists(full_path):
                continue
            path_info = self._get_path_info(full_path)
            if os.path.isdir(full_path):
                path_info['dirname'] = fname
                flist['dirs'].append(path_info)
            elif os.path.isfile(full_path):
                path_info['filename'] = fname
                # Check to see if a filelist update is necessary
                ext = os.path.splitext(fname)[-1].lower()
                gc_path = self.file_paths.get('gcodes', None)
                # Addition 2 START
                if ext == '.ufp':
                    logging.info(full_path + " should be unzipped now!")
                    file = open(full_path, mode='rb')
                    self._unzip_ufp({'full_path':full_path, 'filename':fname, 'body':file.read()})
                    os.remove(full_path)
                    dirty = True
                # Addition 2 END
                if gc_path is not None and full_path.startswith(gc_path) and \
                        ext in VALID_GCODE_EXTS:
                    rel_path = os.path.relpath(full_path, start=gc_path)
                    self.gcode_metadata.parse_metadata(
                        rel_path, path_info['size'], path_info['modified'],
                        notify=True)
                    metadata = self.gcode_metadata.get(rel_path, None)
                    if metadata is not None and is_extended:
                        path_info.update(metadata)
                flist['files'].append(path_info)
        # Addition 3 START
        if dirty:
            return self._list_directory(path, is_extended)
        # Addition 3 END
        usage = shutil.disk_usage(path)
        flist['disk_usage'] = usage._asdict()
        return flist

**Comment by DruckiMcDruck** [comment]
I just ran into this exact issue. I'm using Cura 4.8.0 and Moonraker + Mainsail. As the Cura Octoprint Plugin doesn't work with Moonraker, i setup a samba netshare to save files directly onto the pi. Sadly moonraker doesn't process these files at all, leaving me without preview.

**Comment by Arksine** [comment]
Generally speaking it is intended for users to manage files via the interface.  While its possible to monitor folders, there are some caveats and it can cause real problems depending on how the system is configured.   In the future I may look into an event driven solution where the file manager is notified by the kernel, but that is low priority so I have no timetable on it.  I am however open unzipping a UFP when a directory is refreshed in the UI, similar to the OPs example.

In an ideal world someone will add a Cura plugin with support for Moonraker.  This could be done via direct API support or by using the limited Octoprint APIs Moonraker supports for file uploads.  I don't use Cura nor do I have time to maintain such a plugin so it would need to be user contributed.
