### ISSUE TITLE
Moonraker Error with some Filenames

### ISSUE THREAD

**Issue by icebear74** [Arksine/moonraker#827]
### What happened

Moonraker cant load Preview with some Filenames

### Client

Fluidd

### Browser

Chrome, Firefox

### How to reproduce

![image](https://github.com/Arksine/moonraker/assets/3984852/6de642b9-a455-4783-98f0-9b723e6b1134)
Filename: #12 baby dragon_PLA_3h1m.gcode
seems the Spaces are the Problem :)

**Comment by Arksine** [comment]
There is no log attached, so I can't see the exact error.  FWIW, my test client handles file names with spaces ok.  I suspect that the spaces in the file name need to be escaped by the front end.

**Comment by Arksine** [comment]
As there have been no further comments or updates to this issue I'm going to close this.
