### ISSUE TITLE
Support for Shelly or even MQTT

### ISSUE THREAD

**Issue by nicedevil007** [Arksine/moonraker#84]
Heya, would it be possible to add a Shelly compatibility like you did with Tasmota or TP-Link devices?

A HTTP Command in the shelly universe looks like this:

`http://192.168.1.75/relay/0?turn=off`

The 0 is the number of the relay.

With credentials it looks like this:

`http://user:password@192.168.1.75/relay/0?turn=off`

Most compatibility would we done with MQTT support :) than we can just add nearly everything to turn on/off the printer 💪

**Comment by Arksine** [comment]
While the protocol looks simple enough, I can only add support for devices in which I can test myself.  Support for other devices would need to be contributed (Tasmota was).    I do plan on adding some kind of MQTT support in the future for notifications and there will be hooks for the power plugin.  I don't have a specific timetable on it though.

This overlaps with #30, so I would respectfully ask that future discussion on  MQTT integration move there.

**Comment by nicedevil007** [comment]
Mhhh if I find the right place where you did the part with tasmota I should be able to get it done for Shelly. Than you can integrate it... unfortunately I'm not that familiar with your code 😂 will try and test and then report back!

**Comment by nicedevil007** [comment]
Ok took a look on your tasmota part but didn't get it.... so we can close this and maybe at any time you will release MQTT integration.
