### ISSUE TITLE
Apprise update.

### ISSUE THREAD

**Issue by Rokin05** [Arksine/moonraker#854]
### Is your feature request related to a problem? Please describe

A simple request to ask if it would be possible to push an upgrade from apprise (currently apprise==1.7.1) to v1.7.6 or 1.8.0 in order to benefit from Free-Mobile support.
https://github.com/caronc/apprise/releases

Thank in advance 

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

### Additional information

-

**Comment by nmaggioni** [comment]
Seems to have been done in https://github.com/Arksine/moonraker/commit/64ffe22545ab9c6e2ae0a37b214880de38ba8a2b.

**Comment by Rokin05** [comment]
Nice !, I hadn't paid attention to the maj, I've just tried it manually and it works fine, thanks a lot!
