### ISSUE TITLE
power type `uhubctl` without specifying port

### ISSUE THREAD

**Issue by gongtao0607** [Arksine/moonraker#872]
### What happened

```
[power usb]
type: uhubctl
location: 1-1
port: 1
```
Currently, port and location fields are both mandatory in the config. However, on PI 4B I must not provide port to control the USB power.
```
uhubctl -l 1-1 -a 0
uhubctl -l 1-1 -a 1
```
Please consider make it optional.

### Client

Fluidd

### Browser

Chrome

### How to reproduce

```
[power usb]
type: uhubctl
location: 1-1
```

**Comment by Arksine** [comment]
Thanks.  This should be resolved with commit dfa38a0ddc1ca6025d8903834743c71cb08e2aa1.
