### ISSUE TITLE
Print history has inaccurate “print duration” and “used filament” when using T1

### ISSUE THREAD

**Issue by Dycus** [Arksine/moonraker#878]
### What happened

On the Fluidd print history page, all prints have a correct “total duration”.
Prints using T0 also have correct "print duration" and "used filament".
But prints that use T1 almost always have 0m 0s for print duration, and 0.0mm (or sometimes nonsense, even negative numbers) for used filament.
On occasion, a T1 print will show a correct total duration, but the filament used is still wrong. (A recent print shows 2h 27m 6s / 2h 34m 30s / 58.2 mm for print duration / total duration / filament used. I promise more than 58mm of filament were used in this 2.5hr print.)

I have a dual-extrusion printer (Replicator 2X). I pretty much only use only one tool in a print. I haven't tested this behavior with a dual-extrusion print yet.

I initially reported this issue to the Fluidd team, but they say they pull this data directly from Moonraker and so forwarded me here.

### Client

Fluidd

### Browser

Firefox

### How to reproduce

Run a print that uses only T1 (or probably any non-T0 tool) and check the print statistics/history page once finished.

### Additional information

![image](https://github.com/Arksine/moonraker/assets/5432224/dd121e90-e8b5-46c4-85e1-21a84ac4c458)
[moonraker.log](https://github.com/user-attachments/files/15976464/moonraker.log)
[klippy.log](https://github.com/user-attachments/files/15976467/klippy.log)

**Comment by Arksine** [comment]
As there has been no further feedback I'm going to close this.  If the problem can be reproduced on the official Klipper repo this can be reopened and I will investigate further.
