### ISSUE TITLE
/#/login page creates confusion when user is trusted / authorized

### ISSUE THREAD

**Issue by crabdancing** [Arksine/moonraker#907]
### What happened

Not sure if this is a moonraker or fluidd issue, but when using moonraker+fluidd and accessing over 127.0.0.1 (trusted user), if the user somehow ends up on `http://127:0.0.1/#/login`, they are presented with a login screen, which can easily confuse the user into thinking they are locked out of the account. If you go to `http://127.0.0.1/#` however, the login screen disappears.

### Client

Fluidd

### Browser

Chrome

### How to reproduce

No accounts. Make sure 127.0.0.1 is configured as trusted. Can use SSH reverse tunnel if running klipper/fluidd/moonraker stack remotely. Connect to `http://127.0.0.1/#/login`. Notice that login page appears needlessly. The correct behavior would be to redirect to `http://127.0.0.1/#` because the user is already logged in.

**Comment by Arksine** [comment]
You will need to create an issue on the fluidd repo.  FWIW, it is possible to login as a user even when the host is configured as trusted.  If you are navigating directly to the login screen I'm not sure I would consider the current behavior incorrect, but this would be a discussion you need to have with the Fluidd devs.
