### ISSUE TITLE
Tasmota on Sonoff Basic

### ISSUE THREAD

**Issue by masgar** [Arksine/moonraker#91]
I have a problem with my sonoff basic with tasmota. Power ON/OFF works fine but to get the correct status I had to change the class Tasmota in power.py

from:

self.output_id = config.getint("output_id", 1)

to 

self.output_id = config.getint("output_id", "")

because my sonoff always returns POWER: and never POWER1:

**Comment by Arksine** [comment]
Presumably you need to enable `SetOption26` in Tasmota as outlined in [configuration.md](https://github.com/Arksine/moonraker/blob/master/docs/configuration.md#power).

**Comment by masgar** [comment]
Shame on me. I'm new with tasmota, used to micropython or espeasy. RTFM is always the best way. With SetOption26 enabled it works flawlessly

Tnanks.
